/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgDto } from './wg-dto';
/**
 * 
 * @export
 * @interface ActiveWgsListDto
 */
export interface ActiveWgsListDto {
    /**
     * List of created wargames
     * @type {Array<WgDto>}
     * @memberof ActiveWgsListDto
     */
    createdWgs?: Array<WgDto>;
    /**
     * List of ongoing wargames
     * @type {Array<WgDto>}
     * @memberof ActiveWgsListDto
     */
    ongoingWgs?: Array<WgDto>;
    /**
     * List of finished wargames
     * @type {Array<WgDto>}
     * @memberof ActiveWgsListDto
     */
    finishedWgs?: Array<WgDto>;
}
