/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthRefreshDto
 */
export interface AuthRefreshDto {
    /**
     * Token ID (UUID)
     * @type {string}
     * @memberof AuthRefreshDto
     */
    jti: string;
    /**
     * Associated user ID
     * @type {string}
     * @memberof AuthRefreshDto
     */
    userId: string;
    /**
     * The JWT refresh token string as hash
     * @type {string}
     * @memberof AuthRefreshDto
     */
    hashedRefreshToken: string;
    /**
     * Token expiration timestamp
     * @type {Date}
     * @memberof AuthRefreshDto
     */
    expiresAt: Date;
    /**
     * Token rotation timestamp
     * @type {Date}
     * @memberof AuthRefreshDto
     */
    rotatedAt: Date;
}
