/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EOrderType } from './eorder-type';
/**
 * 
 * @export
 * @interface CreateAerialProtectionOrderDto
 */
export interface CreateAerialProtectionOrderDto {
    /**
     * 
     * @type {EOrderType}
     * @memberof CreateAerialProtectionOrderDto
     */
    type: EOrderType;
    /**
     * Starting or origin territory label
     * @type {string}
     * @memberof CreateAerialProtectionOrderDto
     */
    originTerritory?: string;
    /**
     * Target territory label
     * @type {string}
     * @memberof CreateAerialProtectionOrderDto
     */
    targetTerritory?: string;
    /**
     * Troops engaged in the Order
     * @type {{ [key: string]: number; }}
     * @memberof CreateAerialProtectionOrderDto
     */
    troops?: { [key: string]: number; };
}
