/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateWgMessengerDtoPlayer2PlayerBody
 */
export interface CreateWgMessengerDtoPlayer2PlayerBody {
    /**
     * Recipicent player index
     * @type {number}
     * @memberof CreateWgMessengerDtoPlayer2PlayerBody
     */
    toPlayerIndex: number;
    /**
     * Message content
     * @type {string}
     * @memberof CreateWgMessengerDtoPlayer2PlayerBody
     */
    message?: string;
}
