/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgPlayerStateModel } from './wg-player-state-model';
import { WgTerritoryStateModel } from './wg-territory-state-model';
/**
 * 
 * @export
 * @interface CreateWgStateDto
 */
export interface CreateWgStateDto {
    /**
     * Wargame ID
     * @type {string}
     * @memberof CreateWgStateDto
     */
    wgId?: string;
    /**
     * Phase number for this state
     * @type {number}
     * @memberof CreateWgStateDto
     */
    phase?: number;
    /**
     * Create date of the state
     * @type {Date}
     * @memberof CreateWgStateDto
     */
    createdAt?: Date;
    /**
     * Update date of the state
     * @type {Date}
     * @memberof CreateWgStateDto
     */
    updatedAt?: Date;
    /**
     * Is the wargame over ?
     * @type {boolean}
     * @memberof CreateWgStateDto
     */
    gameOver?: boolean;
    /**
     * Fixed Territory states of the phase by label
     * @type {{ [key: string]: WgTerritoryStateModel; }}
     * @memberof CreateWgStateDto
     */
    territoryStates?: { [key: string]: WgTerritoryStateModel; };
    /**
     * Player states of the phase. Contains all the high level player data in the WG.         The key is the player ID
     * @type {{ [key: string]: WgPlayerStateModel; }}
     * @memberof CreateWgStateDto
     */
    playerStates?: { [key: string]: WgPlayerStateModel; };
    /**
     * Number of locked players in the wg
     * @type {number}
     * @memberof CreateWgStateDto
     */
    lockedPlayersAmount?: number;
    /**
     * Number of active players in the wg
     * @type {number}
     * @memberof CreateWgStateDto
     */
    activePlayersAmount?: number;
}
