/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EOrderType } from './eorder-type';
/**
 * 
 * @export
 * @interface CreateUnfortifyOrderDto
 */
export interface CreateUnfortifyOrderDto {
    /**
     * 
     * @type {EOrderType}
     * @memberof CreateUnfortifyOrderDto
     */
    type: EOrderType;
    /**
     * Starting or origin territory label
     * @type {string}
     * @memberof CreateUnfortifyOrderDto
     */
    originTerritory?: string;
}
