/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ELobbyGameMode } from './elobby-game-mode';
import { ELobbyMapSelection } from './elobby-map-selection';
import { ELobbyVisibility } from './elobby-visibility';
/**
 * 
 * @export
 * @interface CreateLobbyDto
 */
export interface CreateLobbyDto {
    /**
     * 
     * @type {string}
     * @memberof CreateLobbyDto
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLobbyDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateLobbyDto
     */
    playerSlots: number;
    /**
     * 
     * @type {ELobbyGameMode}
     * @memberof CreateLobbyDto
     */
    mode: ELobbyGameMode;
    /**
     * 
     * @type {ELobbyMapSelection}
     * @memberof CreateLobbyDto
     */
    map: ELobbyMapSelection;
    /**
     * 
     * @type {ELobbyVisibility}
     * @memberof CreateLobbyDto
     */
    visibility: ELobbyVisibility;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateLobbyDto
     */
    userIds: Array<string>;
    /**
     * 
     * @type {Array<boolean>}
     * @memberof CreateLobbyDto
     */
    isReady: Array<boolean>;
    /**
     * 
     * @type {string}
     * @memberof CreateLobbyDto
     */
    host: string;
}
