/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EConstructionType } from './econstruction-type';
import { EOrderType } from './eorder-type';
/**
 * 
 * @export
 * @interface CreateDestroyConsOrderDto
 */
export interface CreateDestroyConsOrderDto {
    /**
     * 
     * @type {EOrderType}
     * @memberof CreateDestroyConsOrderDto
     */
    type: EOrderType;
    /**
     * Starting or origin territory label
     * @type {string}
     * @memberof CreateDestroyConsOrderDto
     */
    originTerritory?: string;
    /**
     * 
     * @type {EConstructionType}
     * @memberof CreateDestroyConsOrderDto
     */
    constructionType?: EConstructionType;
    /**
     * Number of constructions to build/destroy
     * @type {number}
     * @memberof CreateDestroyConsOrderDto
     */
    constructionAmount?: number;
}
