/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EAttackTargetType } from './eattack-target-type';
import { EConstructionType } from './econstruction-type';
import { EFortifyStatus } from './efortify-status';
import { EInfraType } from './einfra-type';
import { ELobbyGameMode } from './elobby-game-mode';
import { ELobbyMapSelection } from './elobby-map-selection';
import { ELobbyVisibility } from './elobby-visibility';
import { ELogLevel } from './elog-level';
import { EOrderStatus } from './eorder-status';
import { EOrderType } from './eorder-type';
import { EReportStepType } from './ereport-step-type';
import { ERessourceType } from './eressource-type';
import { ESettingsTypes } from './esettings-types';
import { EWgAdminType } from './ewg-admin-type';
import { EWgBoolParamNames } from './ewg-bool-param-names';
import { EWgCurrencyType } from './ewg-currency-type';
import { EWgFloatParamNames } from './ewg-float-param-names';
import { EWgIntParamNames } from './ewg-int-param-names';
import { EWgMessengerType } from './ewg-messenger-type';
import { EWgUnitType } from './ewg-unit-type';
import { EWgWinLoseTagPresets } from './ewg-win-lose-tag-presets';
/**
 * 
 * @export
 * @interface EnumsSwaggerExport
 */
export interface EnumsSwaggerExport {
    /**
     * 
     * @type {EInfraType}
     * @memberof EnumsSwaggerExport
     */
    eInfraType: EInfraType;
    /**
     * 
     * @type {EConstructionType}
     * @memberof EnumsSwaggerExport
     */
    eConstructionType: EConstructionType;
    /**
     * 
     * @type {EOrderType}
     * @memberof EnumsSwaggerExport
     */
    eOrderType: EOrderType;
    /**
     * 
     * @type {ERessourceType}
     * @memberof EnumsSwaggerExport
     */
    eRessourceType: ERessourceType;
    /**
     * 
     * @type {EWgCurrencyType}
     * @memberof EnumsSwaggerExport
     */
    eCurrencyType: EWgCurrencyType;
    /**
     * 
     * @type {EWgCurrencyType}
     * @memberof EnumsSwaggerExport
     */
    ecurrencyTypeEnum: EWgCurrencyType;
    /**
     * 
     * @type {EWgUnitType}
     * @memberof EnumsSwaggerExport
     */
    eUnitType: EWgUnitType;
    /**
     * 
     * @type {EAttackTargetType}
     * @memberof EnumsSwaggerExport
     */
    ePoundType: EAttackTargetType;
    /**
     * 
     * @type {EOrderStatus}
     * @memberof EnumsSwaggerExport
     */
    eOrderStatus: EOrderStatus;
    /**
     * 
     * @type {EFortifyStatus}
     * @memberof EnumsSwaggerExport
     */
    eFortifyStatus: EFortifyStatus;
    /**
     * 
     * @type {EWgAdminType}
     * @memberof EnumsSwaggerExport
     */
    eWgAdminType: EWgAdminType;
    /**
     * 
     * @type {ELobbyGameMode}
     * @memberof EnumsSwaggerExport
     */
    eLobbyGameMode: ELobbyGameMode;
    /**
     * 
     * @type {ELobbyMapSelection}
     * @memberof EnumsSwaggerExport
     */
    eLobbyMapSelection: ELobbyMapSelection;
    /**
     * 
     * @type {ELobbyVisibility}
     * @memberof EnumsSwaggerExport
     */
    eLobbyVisibility: ELobbyVisibility;
    /**
     * 
     * @type {EReportStepType}
     * @memberof EnumsSwaggerExport
     */
    eReportStepType: EReportStepType;
    /**
     * 
     * @type {EWgWinLoseTagPresets}
     * @memberof EnumsSwaggerExport
     */
    eWgWinLoseTagPresets: EWgWinLoseTagPresets;
    /**
     * 
     * @type {EWgIntParamNames}
     * @memberof EnumsSwaggerExport
     */
    eWgIntParamNames: EWgIntParamNames;
    /**
     * 
     * @type {EWgBoolParamNames}
     * @memberof EnumsSwaggerExport
     */
    eWgBoolParamNames: EWgBoolParamNames;
    /**
     * 
     * @type {EWgFloatParamNames}
     * @memberof EnumsSwaggerExport
     */
    eWgFloatParamNames: EWgFloatParamNames;
    /**
     * 
     * @type {EWgMessengerType}
     * @memberof EnumsSwaggerExport
     */
    eWgMessengerType: EWgMessengerType;
    /**
     * 
     * @type {ELogLevel}
     * @memberof EnumsSwaggerExport
     */
    eLogLevel: ELogLevel;
    /**
     * 
     * @type {ESettingsTypes}
     * @memberof EnumsSwaggerExport
     */
    eSettingsTypes: ESettingsTypes;
}
