/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum EOrderType {
    NONE = 'NONE',
    MOVETROOPS = 'MOVETROOPS',
    MOVEAERIALTROOPS = 'MOVEAERIALTROOPS',
    ATTACK = 'ATTACK',
    POUND = 'POUND',
    BOMB = 'BOMB',
    FORTIFY = 'FORTIFY',
    UNFORTIFY = 'UNFORTIFY',
    SPY = 'SPY',
    SURVEIL = 'SURVEIL',
    MOVESTOCK = 'MOVESTOCK',
    AERIALPROTECTION = 'AERIALPROTECTION',
    BUILDINFRA = 'BUILDINFRA',
    BUILDCONS = 'BUILDCONS',
    DESTROYINFRA = 'DESTROYINFRA',
    DESTROYCONS = 'DESTROYCONS',
    BUYRESSOURCES = 'BUYRESSOURCES',
    SELLRESSOURCES = 'SELLRESSOURCES',
    CANCELORDER = 'CANCELORDER',
    PLAYERFORFEIT = 'PLAYER_FORFEIT'
}

