/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * User status
 * @export
 * @enum {string}
 */
export enum EUserStatus {
    CREATED = 'CREATED',
    ACTIVE = 'ACTIVE',
    DISABLED = 'DISABLED',
    BANNED = 'BANNED',
    DELETED = 'DELETED'
}

