/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum EWgAdminType {
    NONE = 'NONE',
    HANDLERESSOURCES = 'HANDLE_RESSOURCES',
    HANDLECURRENCIES = 'HANDLE_CURRENCIES',
    HANDLECONSTRUCTIONS = 'HANDLE_CONSTRUCTIONS',
    SETINFRATYPE = 'SET_INFRATYPE',
    SETTERRITORYOWNER = 'SET_TERRITORY_OWNER',
    KICKPLAYER = 'KICK_PLAYER'
}

