/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * overall player state
 * @export
 * @enum {string}
 */
export enum EWgPlayerStatus {
    NONE = 'NONE',
    INGAME = 'INGAME',
    WINNER = 'WINNER',
    DEFEATED = 'DEFEATED',
    DRAW = 'DRAW',
    FORFEIT = 'FORFEIT',
    KICKED = 'KICKED'
}

