/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum EWgIntParamNames {
    STARTINGCREDITS = 'STARTING_CREDITS',
    PHASESPERCYCLE = 'PHASES_PER_CYCLE',
    PHASEDURATION = 'PHASE_DURATION',
    MAXPHASEAMOUNT = 'MAX_PHASE_AMOUNT',
    INFLUENCEVICTORYGOAL = 'INFLUENCE_VICTORY_GOAL',
    STRATEGICVICTORYGOAL = 'STRATEGIC_VICTORY_GOAL'
}

