/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum EWgWinLoseTagPresets {
    DEFAULTVICTORY = 'DEFAULT_VICTORY',
    INFLUENCEVICTORY = 'INFLUENCE_VICTORY',
    STRATEGYVICTORY = 'STRATEGY_VICTORY',
    MILITARYVICTORY = 'MILITARY_VICTORY',
    MILITARYDEFEAT = 'MILITARY_DEFEAT',
    DEFEAT = 'DEFEAT',
    FORFEITED = 'FORFEITED',
    KICKED = 'KICKED',
    TIMEDEFEAT = 'TIME_DEFEAT'
}

