/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgTerritoryStateModel } from './wg-territory-state-model';
/**
 * 
 * @export
 * @interface MapDto
 */
export interface MapDto {
    /**
     * Map type name
     * @type {string}
     * @memberof MapDto
     */
    mapName: string;
    /**
     * Version string of the Map to handle multiple versions of Maps during games, note: no dots in this string please
     * @type {string}
     * @memberof MapDto
     */
    version: string;
    /**
     * Dictionnary of startig currencies
     * @type {{ [key: string]: number; }}
     * @memberof MapDto
     */
    startingCurrencies: { [key: string]: number; };
    /**
     * Initial States of all Territories of the Map
     * @type {{ [key: string]: WgTerritoryStateModel; }}
     * @memberof MapDto
     */
    initialTerritoryStates: { [key: string]: WgTerritoryStateModel; };
    /**
     * List of Strategic states for this Map
     * @type {Array<string>}
     * @memberof MapDto
     */
    strategicStates: Array<string>;
    /**
     * List of HQ for this Map. Attached to the Users by order in the list       corresponding to WgModel objects
     * @type {Array<string>}
     * @memberof MapDto
     */
    hqs: Array<string>;
    /**
     * List of Map routes. This field is an oriented graph
     * @type {{ [key: string]: Array<string>; }}
     * @memberof MapDto
     */
    routes: { [key: string]: Array<string>; };
    /**
     * Creation date
     * @type {Date}
     * @memberof MapDto
     */
    createdAt?: Date;
    /**
     * Update date
     * @type {Date}
     * @memberof MapDto
     */
    updatedAt?: Date;
    /**
     * JSON from gsheet
     * @type {any}
     * @memberof MapDto
     */
    createJson?: any;
}
