/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EReportStepType } from './ereport-step-type';
/**
 * 
 * @export
 * @interface OrderReportStep
 */
export interface OrderReportStep {
    /**
     * 
     * @type {{ [key: string]: { [key: string]: number; }; }}
     * @memberof OrderReportStep
     */
    actingTroops?: { [key: string]: { [key: string]: number; }; };
    /**
     * 
     * @type {{ [key: string]: { [key: string]: number; }; }}
     * @memberof OrderReportStep
     */
    passiveTroops?: { [key: string]: { [key: string]: number; }; };
    /**
     * 
     * @type {EReportStepType}
     * @memberof OrderReportStep
     */
    stepType?: EReportStepType;
    /**
     * 
     * @type {number}
     * @memberof OrderReportStep
     */
    phase?: number;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: number; }; }}
     * @memberof OrderReportStep
     */
    troopsAddedOrRemoved?: { [key: string]: { [key: string]: number; }; };
    /**
     * 
     * @type {number}
     * @memberof OrderReportStep
     */
    winnerPlayerIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderReportStep
     */
    previousTargetTerritory?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderReportStep
     */
    targetTerritory?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderReportStep
     */
    bunkers?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderReportStep
     */
    aab?: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof OrderReportStep
     */
    infrasAddedOrRemoved?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof OrderReportStep
     */
    constructionsAddedOrRemoved?: { [key: string]: number; };
    /**
     * 
     * @type {boolean}
     * @memberof OrderReportStep
     */
    fortified?: boolean;
}
