/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PaginatedLinksDocumented
 */
export interface PaginatedLinksDocumented {
    /**
     * 
     * @type {string}
     * @memberof PaginatedLinksDocumented
     */
    first?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLinksDocumented
     */
    previous?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLinksDocumented
     */
    current?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLinksDocumented
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLinksDocumented
     */
    last?: string;
}
