/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PaginatedMetaDocumented
 */
export interface PaginatedMetaDocumented {
    /**
     * 
     * @type {number}
     * @memberof PaginatedMetaDocumented
     */
    itemsPerPage: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedMetaDocumented
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedMetaDocumented
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedMetaDocumented
     */
    totalPages: number;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof PaginatedMetaDocumented
     */
    sortBy?: Array<Array<string>>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PaginatedMetaDocumented
     */
    searchBy?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMetaDocumented
     */
    search?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PaginatedMetaDocumented
     */
    select?: Array<string>;
    /**
     * 
     * @type {any}
     * @memberof PaginatedMetaDocumented
     */
    filter?: any;
}
