/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaginatedLinksDocumented } from './paginated-links-documented';
import { PaginatedMetaDocumented } from './paginated-meta-documented';
/**
 * 
 * @export
 * @interface PaginatedDocumented
 */
export interface PaginatedDocumented {
    /**
     * 
     * @type {Array<any>}
     * @memberof PaginatedDocumented
     */
    data: Array<any>;
    /**
     * 
     * @type {PaginatedMetaDocumented}
     * @memberof PaginatedDocumented
     */
    meta: PaginatedMetaDocumented;
    /**
     * 
     * @type {PaginatedLinksDocumented}
     * @memberof PaginatedDocumented
     */
    links: PaginatedLinksDocumented;
}
