/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EWgGameStatus } from './ewg-game-status';
import { EWgGameType } from './ewg-game-type';
import { WgParametersOverride } from './wg-parameters-override';
/**
 * 
 * @export
 * @interface UpdateWgDto
 */
export interface UpdateWgDto {
    /**
     * Wargame ID
     * @type {string}
     * @memberof UpdateWgDto
     */
    id?: string;
    /**
     * Participating user IDs. The order defines the player index.
     * @type {Array<string>}
     * @memberof UpdateWgDto
     */
    userIds?: Array<string>;
    /**
     * Participating usernames. Should sync with userIds.
     * @type {Array<string>}
     * @memberof UpdateWgDto
     */
    usernames?: Array<string>;
    /**
     * Name of the Planet for this Wargame
     * @type {string}
     * @memberof UpdateWgDto
     */
    planetName?: string;
    /**
     * Name of the Map
     * @type {string}
     * @memberof UpdateWgDto
     */
    mapName?: string;
    /**
     * Version of the Map
     * @type {string}
     * @memberof UpdateWgDto
     */
    mapVersion?: string;
    /**
     * Wargame seed
     * @type {string}
     * @memberof UpdateWgDto
     */
    seed?: string;
    /**
     * Creation date
     * @type {Date}
     * @memberof UpdateWgDto
     */
    createdAt?: Date;
    /**
     * Update date
     * @type {Date}
     * @memberof UpdateWgDto
     */
    updatedAt?: Date;
    /**
     * Start date of the Wargame
     * @type {Date}
     * @memberof UpdateWgDto
     */
    startedAt?: Date;
    /**
     * End date of the Wargame
     * @type {Date}
     * @memberof UpdateWgDto
     */
    finishedAt?: Date;
    /**
     * 
     * @type {WgParametersOverride}
     * @memberof UpdateWgDto
     */
    overrideParameters?: WgParametersOverride;
    /**
     * Current WG Phase
     * @type {number}
     * @memberof UpdateWgDto
     */
    currentPhase?: number;
    /**
     * 
     * @type {EWgGameStatus}
     * @memberof UpdateWgDto
     */
    gameStatus?: EWgGameStatus;
    /**
     * 
     * @type {EWgGameType}
     * @memberof UpdateWgDto
     */
    gameType?: EWgGameType;
    /**
     * Is the Wargame currently resolving?
     * @type {boolean}
     * @memberof UpdateWgDto
     */
    resolving?: boolean;
}
