/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConstructionType } from './construction-type';
import { InfraType } from './infra-type';
import { OrderStatus } from './order-status';
import { WgAdminType } from './wg-admin-type';
/**
 * 
 * @export
 * @interface UpdateWgAdminDto
 */
export interface UpdateWgAdminDto {
    /**
     * Wargame id
     * @type {string}
     * @memberof UpdateWgAdminDto
     */
    wgId?: string;
    /**
     * Phase number for this wgAdmin
     * @type {number}
     * @memberof UpdateWgAdminDto
     */
    phase?: number;
    /**
     * WgAdmin unique id
     * @type {string}
     * @memberof UpdateWgAdminDto
     */
    id?: string;
    /**
     * 
     * @type {WgAdminType}
     * @memberof UpdateWgAdminDto
     */
    type?: WgAdminType;
    /**
     * 
     * @type {OrderStatus}
     * @memberof UpdateWgAdminDto
     */
    status?: OrderStatus;
    /**
     * UserId of the wgAdmin initiator
     * @type {string}
     * @memberof UpdateWgAdminDto
     */
    userId?: string;
    /**
     * PlayerIndex
     * @type {number}
     * @memberof UpdateWgAdminDto
     */
    playerIndex?: number;
    /**
     * Target territory label
     * @type {string}
     * @memberof UpdateWgAdminDto
     */
    territoryLabel?: string;
    /**
     * Troops dict
     * @type {{ [key: string]: number; }}
     * @memberof UpdateWgAdminDto
     */
    troops?: { [key: string]: number; };
    /**
     * Ressources dict
     * @type {{ [key: string]: number; }}
     * @memberof UpdateWgAdminDto
     */
    ressources?: { [key: string]: number; };
    /**
     * Currencies dict
     * @type {{ [key: string]: number; }}
     * @memberof UpdateWgAdminDto
     */
    currencies?: { [key: string]: number; };
    /**
     * Slot index
     * @type {number}
     * @memberof UpdateWgAdminDto
     */
    slot?: number;
    /**
     * 
     * @type {InfraType}
     * @memberof UpdateWgAdminDto
     */
    infraType?: InfraType;
    /**
     * 
     * @type {ConstructionType}
     * @memberof UpdateWgAdminDto
     */
    constructionType?: ConstructionType;
    /**
     * Number of constructions to build/destroy
     * @type {number}
     * @memberof UpdateWgAdminDto
     */
    constructionAmount?: number;
}
