/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgActionDto } from './wg-action-dto';
import { WgAdminDto } from './wg-admin-dto';
import { WgDto } from './wg-dto';
import { WgMessengerDto } from './wg-messenger-dto';
import { WgOrderDto } from './wg-order-dto';
import { WgStateDto } from './wg-state-dto';
/**
 * 
 * @export
 * @interface UpdateWgArchivesDto
 */
export interface UpdateWgArchivesDto {
    /**
     * Wargame ID
     * @type {string}
     * @memberof UpdateWgArchivesDto
     */
    id?: string;
    /**
     * Backend version number used to write this archive
     * @type {string}
     * @memberof UpdateWgArchivesDto
     */
    backendVersion?: string;
    /**
     * Wargame object
     * @type {WgDto}
     * @memberof UpdateWgArchivesDto
     */
    wg?: WgDto;
    /**
     * 
     * @type {Array<WgStateDto>}
     * @memberof UpdateWgArchivesDto
     */
    wgStates?: Array<WgStateDto>;
    /**
     * 
     * @type {Array<WgAdminDto>}
     * @memberof UpdateWgArchivesDto
     */
    wgAdmins?: Array<WgAdminDto>;
    /**
     * 
     * @type {Array<WgActionDto>}
     * @memberof UpdateWgArchivesDto
     */
    wgActions?: Array<WgActionDto>;
    /**
     * 
     * @type {Array<WgOrderDto>}
     * @memberof UpdateWgArchivesDto
     */
    wgOrders?: Array<WgOrderDto>;
    /**
     * 
     * @type {Array<WgMessengerDto>}
     * @memberof UpdateWgArchivesDto
     */
    wgMessengers?: Array<WgMessengerDto>;
    /**
     * Creation date
     * @type {Date}
     * @memberof UpdateWgArchivesDto
     */
    createdAt?: Date;
    /**
     * Update date
     * @type {Date}
     * @memberof UpdateWgArchivesDto
     */
    updatedAt?: Date;
}
