/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgInfraStateModel } from './wg-infra-state-model';
/**
 * 
 * @export
 * @interface UpdateWgActionDto
 */
export interface UpdateWgActionDto {
    /**
     * Wargame of the order
     * @type {string}
     * @memberof UpdateWgActionDto
     */
    wgId?: string;
    /**
     * Phase number for this order
     * @type {number}
     * @memberof UpdateWgActionDto
     */
    phase?: number;
    /**
     * Action territory label
     * @type {string}
     * @memberof UpdateWgActionDto
     */
    territory?: string;
    /**
     * PlayerIndex of the order initiator
     * @type {number}
     * @memberof UpdateWgActionDto
     */
    playerIndex?: number;
    /**
     * Mine states by MineType
     * @type {{ [key: string]: number; }}
     * @memberof UpdateWgActionDto
     */
    mineStates?: { [key: string]: number; };
    /**
     * InfraStates by slot number
     * @type {{ [key: string]: WgInfraStateModel; }}
     * @memberof UpdateWgActionDto
     */
    infraStates?: { [key: string]: WgInfraStateModel; };
}
