/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EAttackTargetType } from './eattack-target-type';
import { EConstructionType } from './econstruction-type';
import { EOrderStatus } from './eorder-status';
import { EOrderType } from './eorder-type';
import { EWgInfraType } from './ewg-infra-type';
import { OrderReportStep } from './order-report-step';
/**
 * 
 * @export
 * @interface UpdateWgOrderDto
 */
export interface UpdateWgOrderDto {
    /**
     * Wargame id
     * @type {string}
     * @memberof UpdateWgOrderDto
     */
    wgId?: string;
    /**
     * Phase number key for this order
     * @type {number}
     * @memberof UpdateWgOrderDto
     */
    phase?: number;
    /**
     * Order consistant id
     * @type {string}
     * @memberof UpdateWgOrderDto
     */
    orderId?: string;
    /**
     * 
     * @type {EOrderStatus}
     * @memberof UpdateWgOrderDto
     */
    status?: EOrderStatus;
    /**
     * 
     * @type {EOrderType}
     * @memberof UpdateWgOrderDto
     */
    type?: EOrderType;
    /**
     * UserId of the order initiator
     * @type {string}
     * @memberof UpdateWgOrderDto
     */
    userId?: string;
    /**
     * PlayerIndex of the order initiator
     * @type {number}
     * @memberof UpdateWgOrderDto
     */
    playerIndex?: number;
    /**
     * Can the user cancel the order ?
     * @type {boolean}
     * @memberof UpdateWgOrderDto
     */
    cancelable?: boolean;
    /**
     * Phase where the order was created
     * @type {number}
     * @memberof UpdateWgOrderDto
     */
    startPhase?: number;
    /**
     * Phase where the order will be resolved and closed
     * @type {number}
     * @memberof UpdateWgOrderDto
     */
    resolutionPhase?: number;
    /**
     * Starting or origin territory label
     * @type {string}
     * @memberof UpdateWgOrderDto
     */
    originTerritory?: string;
    /**
     * Target territory label
     * @type {string}
     * @memberof UpdateWgOrderDto
     */
    targetTerritory?: string;
    /**
     * Target Order consistant id
     * @type {string}
     * @memberof UpdateWgOrderDto
     */
    targetOrderId?: string;
    /**
     * Current territory label
     * @type {string}
     * @memberof UpdateWgOrderDto
     */
    currentTerritory?: string;
    /**
     * Troops engaged in the Order
     * @type {{ [key: string]: number; }}
     * @memberof UpdateWgOrderDto
     */
    troops?: { [key: string]: number; };
    /**
     * Ressources engaged in the order
     * @type {{ [key: string]: number; }}
     * @memberof UpdateWgOrderDto
     */
    ressources?: { [key: string]: number; };
    /**
     * Slot index
     * @type {number}
     * @memberof UpdateWgOrderDto
     */
    slot?: number;
    /**
     * 
     * @type {EWgInfraType}
     * @memberof UpdateWgOrderDto
     */
    infraType?: EWgInfraType;
    /**
     * 
     * @type {EConstructionType}
     * @memberof UpdateWgOrderDto
     */
    constructionType?: EConstructionType;
    /**
     * 
     * @type {EAttackTargetType}
     * @memberof UpdateWgOrderDto
     */
    attackTargetType?: EAttackTargetType;
    /**
     * Number of constructions to build/destroy
     * @type {number}
     * @memberof UpdateWgOrderDto
     */
    constructionAmount?: number;
    /**
     * Indicate the current report over the order status
     * @type {Array<OrderReportStep>}
     * @memberof UpdateWgOrderDto
     */
    reportSteps?: Array<OrderReportStep>;
}
