/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EUserRole } from './euser-role';
import { EUserStatus } from './euser-status';
/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    id: string;
    /**
     * Ingame player name. Important: ensure unicity
     * @type {string}
     * @memberof UserDto
     */
    username: string;
    /**
     * User email. Important: ensure unicity
     * @type {string}
     * @memberof UserDto
     */
    email: string;
    /**
     * 
     * @type {EUserStatus}
     * @memberof UserDto
     */
    status: EUserStatus;
    /**
     * 
     * @type {Array<EUserRole>}
     * @memberof UserDto
     */
    roles: Array<EUserRole>;
    /**
     * User email or username
     * @type {string}
     * @memberof UserDto
     */
    usernameOrEmail?: string;
    /**
     * User password
     * @type {string}
     * @memberof UserDto
     */
    password?: string;
    /**
     * User confirmPassword
     * @type {string}
     * @memberof UserDto
     */
    confirmPassword?: string;
    /**
     * User previousPassword
     * @type {string}
     * @memberof UserDto
     */
    previousPassword?: string;
    /**
     * Unique nounce to sign for authentication
     * @type {string}
     * @memberof UserDto
     */
    cryptedPassword?: string;
    /**
     * Creation date
     * @type {Date}
     * @memberof UserDto
     */
    createdAt?: Date;
    /**
     * Update date
     * @type {Date}
     * @memberof UserDto
     */
    updatedAt?: Date;
}
