/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserLoginDto
 */
export interface UserLoginDto {
    /**
     * User email or username
     * @type {string}
     * @memberof UserLoginDto
     */
    usernameOrEmail?: string;
    /**
     * User password
     * @type {string}
     * @memberof UserLoginDto
     */
    password?: string;
}
