/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserRegisterDto
 */
export interface UserRegisterDto {
    /**
     * Ingame player name. Important: ensure unicity
     * @type {string}
     * @memberof UserRegisterDto
     */
    username: string;
    /**
     * User email. Important: ensure unicity
     * @type {string}
     * @memberof UserRegisterDto
     */
    email: string;
    /**
     * User password
     * @type {string}
     * @memberof UserRegisterDto
     */
    password?: string;
    /**
     * User confirmPassword
     * @type {string}
     * @memberof UserRegisterDto
     */
    confirmPassword?: string;
}
