/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserPasswordChangeDto
 */
export interface UserPasswordChangeDto {
    /**
     * User password
     * @type {string}
     * @memberof UserPasswordChangeDto
     */
    password?: string;
    /**
     * User confirmPassword
     * @type {string}
     * @memberof UserPasswordChangeDto
     */
    confirmPassword?: string;
    /**
     * User previousPassword
     * @type {string}
     * @memberof UserPasswordChangeDto
     */
    previousPassword?: string;
}
