/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EUserRole } from './euser-role';
/**
 * 
 * @export
 * @interface UserPublicInfoDto
 */
export interface UserPublicInfoDto {
    /**
     * 
     * @type {string}
     * @memberof UserPublicInfoDto
     */
    id: string;
    /**
     * Ingame player name. Important: ensure unicity
     * @type {string}
     * @memberof UserPublicInfoDto
     */
    username: string;
    /**
     * 
     * @type {Array<EUserRole>}
     * @memberof UserPublicInfoDto
     */
    roles: Array<EUserRole>;
}
