/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Condition type
 * @export
 * @enum {string}
 */
export enum WgConditionType {
    NONE = 'NONE',
    OWNSTERRITORY = 'OWNS_TERRITORY',
    OWNSSTRATEGIC = 'OWNS_STRATEGIC',
    OWNSRESSOURCE = 'OWNS_RESSOURCE',
    OWNSUNIT = 'OWNS_UNIT',
    OWNSINFRA = 'OWNS_INFRA',
    OWNSCURRENCY = 'OWNS_CURRENCY',
    OWNSSTARTINGHQ = 'OWNS_STARTING_HQ',
    LASTALIVE = 'LAST_ALIVE'
}

