/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgConstructionModel } from './wg-construction-model';
import { WgInfraModel } from './wg-infra-model';
import { WgMineModel } from './wg-mine-model';
import { WgUnitModel } from './wg-unit-model';
/**
 * 
 * @export
 * @interface WgComplexParameters
 */
export interface WgComplexParameters {
    /**
     * Infra properties
     * @type {{ [key: string]: WgInfraModel; }}
     * @memberof WgComplexParameters
     */
    infraParameters: { [key: string]: WgInfraModel; };
    /**
     * Construction properties
     * @type {{ [key: string]: WgConstructionModel; }}
     * @memberof WgComplexParameters
     */
    constructionParameters: { [key: string]: WgConstructionModel; };
    /**
     * Mine properties
     * @type {{ [key: string]: WgMineModel; }}
     * @memberof WgComplexParameters
     */
    mineParameters: { [key: string]: WgMineModel; };
    /**
     * Unit properties
     * @type {{ [key: string]: WgUnitModel; }}
     * @memberof WgComplexParameters
     */
    unitParameters: { [key: string]: WgUnitModel; };
}
