/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgConditionPhaseCounterType } from './wg-condition-phase-counter-type';
/**
 * 
 * @export
 * @interface WgConditionPhaseCounter
 */
export interface WgConditionPhaseCounter {
    /**
     * 
     * @type {WgConditionPhaseCounterType}
     * @memberof WgConditionPhaseCounter
     */
    phaseCounterType: WgConditionPhaseCounterType;
    /**
     * phase number
     * @type {number}
     * @memberof WgConditionPhaseCounter
     */
    phaseNumber: number;
}
