/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CurrencyType } from './currency-type';
import { InfraType } from './infra-type';
import { RessourceType } from './ressource-type';
import { UnitType } from './unit-type';
import { WgConditionType } from './wg-condition-type';
/**
 * 
 * @export
 * @interface WgConditionDto
 */
export interface WgConditionDto {
    /**
     * 
     * @type {WgConditionType}
     * @memberof WgConditionDto
     */
    type?: WgConditionType;
    /**
     * Invert condition ?
     * @type {boolean}
     * @memberof WgConditionDto
     */
    invert?: boolean;
    /**
     * Territory label
     * @type {string}
     * @memberof WgConditionDto
     */
    territoryLabel?: string;
    /**
     * Amount
     * @type {number}
     * @memberof WgConditionDto
     */
    amount?: number;
    /**
     * 
     * @type {InfraType}
     * @memberof WgConditionDto
     */
    infraType?: InfraType;
    /**
     * 
     * @type {UnitType}
     * @memberof WgConditionDto
     */
    unitType?: UnitType;
    /**
     * 
     * @type {RessourceType}
     * @memberof WgConditionDto
     */
    ressourceType?: RessourceType;
    /**
     * 
     * @type {CurrencyType}
     * @memberof WgConditionDto
     */
    currencyType?: CurrencyType;
}
