/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EWgGameStatus } from './ewg-game-status';
import { EWgGameType } from './ewg-game-type';
import { WgParametersOverride } from './wg-parameters-override';
/**
 * 
 * @export
 * @interface WgDto
 */
export interface WgDto {
    /**
     * Wargame ID
     * @type {string}
     * @memberof WgDto
     */
    id: string;
    /**
     * Participating user IDs. The order defines the player index.
     * @type {Array<string>}
     * @memberof WgDto
     */
    userIds: Array<string>;
    /**
     * Participating usernames. Should sync with userIds.
     * @type {Array<string>}
     * @memberof WgDto
     */
    usernames: Array<string>;
    /**
     * Name of the Planet for this Wargame
     * @type {string}
     * @memberof WgDto
     */
    planetName: string;
    /**
     * Name of the Map
     * @type {string}
     * @memberof WgDto
     */
    mapName: string;
    /**
     * Version of the Map
     * @type {string}
     * @memberof WgDto
     */
    mapVersion: string;
    /**
     * Wargame seed
     * @type {string}
     * @memberof WgDto
     */
    seed: string;
    /**
     * Creation date
     * @type {Date}
     * @memberof WgDto
     */
    createdAt?: Date;
    /**
     * Update date
     * @type {Date}
     * @memberof WgDto
     */
    updatedAt?: Date;
    /**
     * Start date of the Wargame
     * @type {Date}
     * @memberof WgDto
     */
    startedAt?: Date;
    /**
     * End date of the Wargame
     * @type {Date}
     * @memberof WgDto
     */
    finishedAt?: Date;
    /**
     * 
     * @type {WgParametersOverride}
     * @memberof WgDto
     */
    overrideParameters?: WgParametersOverride;
    /**
     * Current WG Phase
     * @type {number}
     * @memberof WgDto
     */
    currentPhase: number;
    /**
     * 
     * @type {EWgGameStatus}
     * @memberof WgDto
     */
    gameStatus: EWgGameStatus;
    /**
     * 
     * @type {EWgGameType}
     * @memberof WgDto
     */
    gameType: EWgGameType;
    /**
     * Is the Wargame currently resolving?
     * @type {boolean}
     * @memberof WgDto
     */
    resolving: boolean;
}
