/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WgGatewayDto
 */
export interface WgGatewayDto {
    /**
     * Wargame id
     * @type {string}
     * @memberof WgGatewayDto
     */
    wgId?: string;
    /**
     * Phase number for this wgGatewayDto
     * @type {number}
     * @memberof WgGatewayDto
     */
    phase?: number;
    /**
     * user unique id
     * @type {string}
     * @memberof WgGatewayDto
     */
    userId?: string;
}
