/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MapDto } from './map-dto';
import { WgDto } from './wg-dto';
import { WgMessengerDto } from './wg-messenger-dto';
import { WgOrderDto } from './wg-order-dto';
import { WgParameters } from './wg-parameters';
import { WgStateDto } from './wg-state-dto';
/**
 * 
 * @export
 * @interface WgGroupedDto
 */
export interface WgGroupedDto {
    /**
     * 
     * @type {WgDto}
     * @memberof WgGroupedDto
     */
    wg: WgDto;
    /**
     * 
     * @type {MapDto}
     * @memberof WgGroupedDto
     */
    map: MapDto;
    /**
     * 
     * @type {WgParameters}
     * @memberof WgGroupedDto
     */
    wgParameters: WgParameters;
    /**
     * 
     * @type {WgStateDto}
     * @memberof WgGroupedDto
     */
    filteredState: WgStateDto;
    /**
     * 
     * @type {Array<WgOrderDto>}
     * @memberof WgGroupedDto
     */
    ordersOngoing: Array<WgOrderDto>;
    /**
     * 
     * @type {Array<WgOrderDto>}
     * @memberof WgGroupedDto
     */
    ordersDone: Array<WgOrderDto>;
    /**
     * 
     * @type {Array<WgMessengerDto>}
     * @memberof WgGroupedDto
     */
    messengers: Array<WgMessengerDto>;
    /**
     * 
     * @type {Array<number>}
     * @memberof WgGroupedDto
     */
    mutes: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof WgGroupedDto
     */
    remainingSeconds: number;
}
