/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EInfraBuildStatus } from './einfra-build-status';
import { EWgInfraType } from './ewg-infra-type';
/**
 * 
 * @export
 * @interface WgInfraStateModel
 */
export interface WgInfraStateModel {
    /**
     * 
     * @type {EInfraBuildStatus}
     * @memberof WgInfraStateModel
     */
    infraBuildStatus: EInfraBuildStatus;
    /**
     * 
     * @type {EWgInfraType}
     * @memberof WgInfraStateModel
     */
    infraType: EWgInfraType;
    /**
     * Infra construction advancement in percent
     * @type {number}
     * @memberof WgInfraStateModel
     */
    inConstructionPercentage?: number;
    /**
     * Infra active or not
     * @type {boolean}
     * @memberof WgInfraStateModel
     */
    isActive?: boolean;
    /**
     * Selected recipe
     * @type {string}
     * @memberof WgInfraStateModel
     */
    selectedRecipe?: string;
    /**
     * Number of reserved workers
     * @type {number}
     * @memberof WgInfraStateModel
     */
    workers?: number;
}
