/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgPriceModel } from './wg-price-model';
import { WgRecipe } from './wg-recipe';
/**
 * 
 * @export
 * @interface WgInfraModel
 */
export interface WgInfraModel {
    /**
     * 
     * @type {WgPriceModel}
     * @memberof WgInfraModel
     */
    price: WgPriceModel;
    /**
     * 
     * @type {WgPriceModel}
     * @memberof WgInfraModel
     */
    upkeep?: WgPriceModel;
    /**
     * Building phase duration
     * @type {number}
     * @memberof WgInfraModel
     */
    buildDuration: number;
    /**
     * Infra max population
     * @type {number}
     * @memberof WgInfraModel
     */
    populationMax: number;
    /**
     * Infra resistance to damages
     * @type {number}
     * @memberof WgInfraModel
     */
    resistance: number;
    /**
     * Infra recipes
     * @type {Array<WgRecipe>}
     * @memberof WgInfraModel
     */
    recipes: Array<WgRecipe>;
}
