/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WgLockDto
 */
export interface WgLockDto {
    /**
     * Wargame ID
     * @type {string}
     * @memberof WgLockDto
     */
    wgId: string;
    /**
     * Phase of the locks
     * @type {number}
     * @memberof WgLockDto
     */
    phase: number;
    /**
     * Locked player indices
     * @type {Array<number>}
     * @memberof WgLockDto
     */
    locks: Array<number>;
}
