/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WgMuteDto
 */
export interface WgMuteDto {
    /**
     * Wargame id
     * @type {string}
     * @memberof WgMuteDto
     */
    wgId: string;
    /**
     * PlayerIndex of the muter
     * @type {number}
     * @memberof WgMuteDto
     */
    muterPlayerIndex: number;
    /**
     * PlayerIndex of the muted
     * @type {number}
     * @memberof WgMuteDto
     */
    mutedPlayerIndex: number;
}
