/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EReportType } from './ereport-type';
import { EWgMessengerType } from './ewg-messenger-type';
import { OrderReportStep } from './order-report-step';
import { WgOrderDto } from './wg-order-dto';
/**
 * 
 * @export
 * @interface WgMessengerDto
 */
export interface WgMessengerDto {
    /**
     * Wargame id
     * @type {string}
     * @memberof WgMessengerDto
     */
    wgId: string;
    /**
     * Creation date
     * @type {Date}
     * @memberof WgMessengerDto
     */
    createdAt?: Date;
    /**
     * Update date
     * @type {Date}
     * @memberof WgMessengerDto
     */
    updatedAt?: Date;
    /**
     * Phase number for this order
     * @type {number}
     * @memberof WgMessengerDto
     */
    phase: number;
    /**
     * Message id
     * @type {string}
     * @memberof WgMessengerDto
     */
    id: string;
    /**
     * 
     * @type {EWgMessengerType}
     * @memberof WgMessengerDto
     */
    type: EWgMessengerType;
    /**
     * Recipicent player index
     * @type {number}
     * @memberof WgMessengerDto
     */
    toPlayerIndex: number;
    /**
     * Sender player index
     * @type {number}
     * @memberof WgMessengerDto
     */
    fromPlayerIndex?: number;
    /**
     * Message content
     * @type {string}
     * @memberof WgMessengerDto
     */
    message?: string;
    /**
     * 
     * @type {WgOrderDto}
     * @memberof WgMessengerDto
     */
    order?: WgOrderDto;
    /**
     * 
     * @type {EReportType}
     * @memberof WgMessengerDto
     */
    reportType?: EReportType;
    /**
     * Report steps
     * @type {Array<OrderReportStep>}
     * @memberof WgMessengerDto
     */
    reportSteps?: Array<OrderReportStep>;
}
