/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WgMigrationImportOptionsDto
 */
export interface WgMigrationImportOptionsDto {
    /**
     * Skip admins during the migration
     * @type {boolean}
     * @memberof WgMigrationImportOptionsDto
     */
    skipAdmins?: boolean;
    /**
     * Skip actions during the migration
     * @type {boolean}
     * @memberof WgMigrationImportOptionsDto
     */
    skipActions?: boolean;
    /**
     * Skip orders during the migration
     * @type {boolean}
     * @memberof WgMigrationImportOptionsDto
     */
    skipOrders?: boolean;
    /**
     * Skip all messengers during the migration
     * @type {boolean}
     * @memberof WgMigrationImportOptionsDto
     */
    skipAllMessengers?: boolean;
    /**
     * Skip messenger types during the migration
     * @type {Array<string>}
     * @memberof WgMigrationImportOptionsDto
     */
    skipMessengerTypes?: Array<string>;
    /**
     * Remap the original userIds to test user ids
     * @type {boolean}
     * @memberof WgMigrationImportOptionsDto
     */
    remapUsers?: boolean;
    /**
     * Disable previous username append in the wg username field : test2(username)
     * @type {boolean}
     * @memberof WgMigrationImportOptionsDto
     */
    removeUsernames?: boolean;
    /**
     * Planet name prefix : IMPORT(oldPlanetName)
     * @type {string}
     * @memberof WgMigrationImportOptionsDto
     */
    planetNamePrefix?: string;
}
