/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WgMigrationExportOptionsDto
 */
export interface WgMigrationExportOptionsDto {
    /**
     * Skip admins during the migration
     * @type {boolean}
     * @memberof WgMigrationExportOptionsDto
     */
    skipAdmins?: boolean;
    /**
     * Skip actions during the migration
     * @type {boolean}
     * @memberof WgMigrationExportOptionsDto
     */
    skipActions?: boolean;
    /**
     * Skip orders during the migration
     * @type {boolean}
     * @memberof WgMigrationExportOptionsDto
     */
    skipOrders?: boolean;
    /**
     * Skip all messengers during the migration
     * @type {boolean}
     * @memberof WgMigrationExportOptionsDto
     */
    skipAllMessengers?: boolean;
    /**
     * Skip messenger types during the migration
     * @type {Array<string>}
     * @memberof WgMigrationExportOptionsDto
     */
    skipMessengerTypes?: Array<string>;
    /**
     * Compress the export as gzip binary
     * @type {boolean}
     * @memberof WgMigrationExportOptionsDto
     */
    compress?: boolean;
}
