/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EWgPlayerStatus } from './ewg-player-status';
import { EWgWinLoseTagPresets } from './ewg-win-lose-tag-presets';
/**
 * 
 * @export
 * @interface WgPlayerStateModel
 */
export interface WgPlayerStateModel {
    /**
     * This user owned currencies
     * @type {{ [key: string]: number; }}
     * @memberof WgPlayerStateModel
     */
    currencies?: { [key: string]: number; };
    /**
     * The label of the starting HQ of this player
     * @type {string}
     * @memberof WgPlayerStateModel
     */
    startingHq: string;
    /**
     * Win/Lose condition tracking
     * @type {{ [key: string]: number; }}
     * @memberof WgPlayerStateModel
     */
    conditionCounters?: { [key: string]: number; };
    /**
     * Has the player locked his phase
     * @type {boolean}
     * @memberof WgPlayerStateModel
     */
    lockedPhase: boolean;
    /**
     * 
     * @type {EWgPlayerStatus}
     * @memberof WgPlayerStateModel
     */
    status?: EWgPlayerStatus;
    /**
     * 
     * @type {EWgWinLoseTagPresets}
     * @memberof WgPlayerStateModel
     */
    winLoseTag?: EWgWinLoseTagPresets;
    /**
     * Indexes of players this player has muted in this match
     * @type {Array<number>}
     * @memberof WgPlayerStateModel
     */
    mutedPlayerIndexes?: Array<number>;
}
