/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgComplexParameters } from './wg-complex-parameters';
import { WgWinLoseParameters } from './wg-win-lose-parameters';
/**
 * 
 * @export
 * @interface WgParameters
 */
export interface WgParameters {
    /**
     * Wargame integer parameters
     * @type {{ [key: string]: number; }}
     * @memberof WgParameters
     */
    integerParameters: { [key: string]: number; };
    /**
     * Wargame float parameters
     * @type {{ [key: string]: number; }}
     * @memberof WgParameters
     */
    floatParameters: { [key: string]: number; };
    /**
     * Wargame bool parameters
     * @type {{ [key: string]: boolean; }}
     * @memberof WgParameters
     */
    boolParameters: { [key: string]: boolean; };
    /**
     * Wargame orders duration
     * @type {{ [key: string]: number; }}
     * @memberof WgParameters
     */
    orderDurations: { [key: string]: number; };
    /**
     * 
     * @type {WgComplexParameters}
     * @memberof WgParameters
     */
    complexParameters: WgComplexParameters;
    /**
     * 
     * @type {WgWinLoseParameters}
     * @memberof WgParameters
     */
    winLoseParameters: WgWinLoseParameters;
}
