/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WgPriceModel
 */
export interface WgPriceModel {
    /**
     * Describes the price of something
     * @type {{ [key: string]: number; }}
     * @memberof WgPriceModel
     */
    cost: { [key: string]: number; };
}
