/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgPriceModel } from './wg-price-model';
/**
 * 
 * @export
 * @interface WgRecipe
 */
export interface WgRecipe {
    /**
     * Production type
     * @type {string}
     * @memberof WgRecipe
     */
    prodType: string;
    /**
     * 
     * @type {WgPriceModel}
     * @memberof WgRecipe
     */
    prodPrice?: WgPriceModel;
    /**
     * Max production of the recipe
     * @type {number}
     * @memberof WgRecipe
     */
    prodMax: number;
}
