/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgConditionDto } from './wg-condition-dto';
import { WgConditionPhaseCounter } from './wg-condition-phase-counter';
/**
 * 
 * @export
 * @interface WgSingleCondition
 */
export interface WgSingleCondition {
    /**
     * Condition Name/Tag
     * @type {string}
     * @memberof WgSingleCondition
     */
    name: string;
    /**
     * 
     * @type {WgConditionDto}
     * @memberof WgSingleCondition
     */
    conditionDto: WgConditionDto;
    /**
     * 
     * @type {WgConditionPhaseCounter}
     * @memberof WgSingleCondition
     */
    phaseCounter?: WgConditionPhaseCounter;
}
