/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EFortifyStatus } from './efortify-status';
import { WgInfraStateModel } from './wg-infra-state-model';
/**
 * 
 * @export
 * @interface WgTerritoryStateModel
 */
export interface WgTerritoryStateModel {
    /**
     * Player index of owner of the territory, points to constant if neutral, actually defaults to -1
     * @type {number}
     * @memberof WgTerritoryStateModel
     */
    ownerIndex: number;
    /**
     * Number of infrastructure slots
     * @type {number}
     * @memberof WgTerritoryStateModel
     */
    slots: number;
    /**
     * Total territory population
     * @type {number}
     * @memberof WgTerritoryStateModel
     */
    population: number;
    /**
     * Current available territory population
     * @type {number}
     * @memberof WgTerritoryStateModel
     */
    availablePop: number;
    /**
     * 
     * @type {EFortifyStatus}
     * @memberof WgTerritoryStateModel
     */
    fortifyStatus: EFortifyStatus;
    /**
     * List of all ressources
     * @type {{ [key: string]: number; }}
     * @memberof WgTerritoryStateModel
     */
    ressources: { [key: string]: number; };
    /**
     * List of all mines and their population
     * @type {{ [key: string]: number; }}
     * @memberof WgTerritoryStateModel
     */
    mines?: { [key: string]: number; };
    /**
     * Map of all infraStates by slotID
     * @type {{ [key: string]: WgInfraStateModel; }}
     * @memberof WgTerritoryStateModel
     */
    infraStates: { [key: string]: WgInfraStateModel; };
    /**
     * Map of constructions amount by ConstructionType
     * @type {{ [key: string]: number; }}
     * @memberof WgTerritoryStateModel
     */
    consAmount: { [key: string]: number; };
    /**
     * Troop state of the territory by playerIndex
     * @type {{ [key: string]: { [key: string]: number; }; }}
     * @memberof WgTerritoryStateModel
     */
    troopStates: { [key: string]: { [key: string]: number; }; };
}
