/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgPriceModel } from './wg-price-model';
/**
 * 
 * @export
 * @interface WgUnitModel
 */
export interface WgUnitModel {
    /**
     * 
     * @type {WgPriceModel}
     * @memberof WgUnitModel
     */
    upkeep: WgPriceModel;
    /**
     * Melee attack attribute
     * @type {number}
     * @memberof WgUnitModel
     */
    melee: number;
    /**
     * Defense attribute
     * @type {number}
     * @memberof WgUnitModel
     */
    defense: number;
    /**
     * Range attack attribute
     * @type {number}
     * @memberof WgUnitModel
     */
    range: number;
    /**
     * Resistance attribute
     * @type {number}
     * @memberof WgUnitModel
     */
    resistance: number;
}
