/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WgSingleCondition } from './wg-single-condition';
/**
 * 
 * @export
 * @interface WgWinLoseParameters
 */
export interface WgWinLoseParameters {
    /**
     * List of global win conditions
     * @type {Array<WgSingleCondition>}
     * @memberof WgWinLoseParameters
     */
    globalWinConditions?: Array<WgSingleCondition>;
    /**
     * List of global lose conditions
     * @type {Array<WgSingleCondition>}
     * @memberof WgWinLoseParameters
     */
    globalLoseConditions?: Array<WgSingleCondition>;
    /**
     * List of per playerIndex win conditions
     * @type {{ [key: string]: WgSingleCondition; }}
     * @memberof WgWinLoseParameters
     */
    perIndexWinConditions?: { [key: string]: WgSingleCondition; };
    /**
     * List of per playerIndex lose conditions
     * @type {{ [key: string]: WgSingleCondition; }}
     * @memberof WgWinLoseParameters
     */
    perIndexLoseConditions?: { [key: string]: WgSingleCondition; };
}
