/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/authentication-api';
export * from './apis/default-api';
export * from './apis/env-api';
export * from './apis/lobby-api';
export * from './apis/mailer-wp-api';
export * from './apis/maps-api';
export * from './apis/settings-api';
export * from './apis/users-api';
export * from './apis/users-account-api';
export * from './apis/users-wg-list-api';
export * from './apis/wargames-api';
export * from './apis/wargames-actions-api';
export * from './apis/wargames-archives-api';
export * from './apis/wargames-locks-api';
export * from './apis/wargames-messenger-api';
export * from './apis/wargames-mutes-api';
export * from './apis/wargames-orders-api';
export * from './apis/wg-resolution-api';

