/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { JwtTokens } from '../models';
import { UserLoginDto } from '../models';
import { UserPublicInfoDto } from '../models';
import { UserRegisterDto } from '../models';
/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {UserLoginDto} body 
         * @param {string} [xClientType] Client type header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerUserLogin: async (body: UserLoginDto, xClientType?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling authControllerUserLogin.');
            }
            const localVarPath = `/v1/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xClientType !== undefined && xClientType !== null) {
                localVarHeaderParameter['x-client-type'] = String(xClientType);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {JwtTokens} [body] 
         * @param {string} [xClientType] Client type header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerUserRefresh: async (body?: JwtTokens, xClientType?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xClientType !== undefined && xClientType !== null) {
                localVarHeaderParameter['x-client-type'] = String(xClientType);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register a new user
         * @param {UserRegisterDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerUserRegister: async (body: UserRegisterDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling authControllerUserRegister.');
            }
            const localVarPath = `/v1/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {JwtTokens} [body] 
         * @param {string} [xClientType] Client type header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerUserRevoke: async (body?: JwtTokens, xClientType?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/auth/revoke`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xClientType !== undefined && xClientType !== null) {
                localVarHeaderParameter['x-client-type'] = String(xClientType);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {UserLoginDto} body 
         * @param {string} [xClientType] Client type header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerUserLogin(body: UserLoginDto, xClientType?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<JwtTokens>>> {
            const localVarAxiosArgs = await AuthenticationApiAxiosParamCreator(configuration).authControllerUserLogin(body, xClientType, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {JwtTokens} [body] 
         * @param {string} [xClientType] Client type header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerUserRefresh(body?: JwtTokens, xClientType?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<JwtTokens>>> {
            const localVarAxiosArgs = await AuthenticationApiAxiosParamCreator(configuration).authControllerUserRefresh(body, xClientType, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Register a new user
         * @param {UserRegisterDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerUserRegister(body: UserRegisterDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserPublicInfoDto>>> {
            const localVarAxiosArgs = await AuthenticationApiAxiosParamCreator(configuration).authControllerUserRegister(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {JwtTokens} [body] 
         * @param {string} [xClientType] Client type header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerUserRevoke(body?: JwtTokens, xClientType?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<JwtTokens>>> {
            const localVarAxiosArgs = await AuthenticationApiAxiosParamCreator(configuration).authControllerUserRevoke(body, xClientType, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {UserLoginDto} body 
         * @param {string} [xClientType] Client type header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerUserLogin(body: UserLoginDto, xClientType?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<JwtTokens>> {
            return AuthenticationApiFp(configuration).authControllerUserLogin(body, xClientType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {JwtTokens} [body] 
         * @param {string} [xClientType] Client type header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerUserRefresh(body?: JwtTokens, xClientType?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<JwtTokens>> {
            return AuthenticationApiFp(configuration).authControllerUserRefresh(body, xClientType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register a new user
         * @param {UserRegisterDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerUserRegister(body: UserRegisterDto, options?: AxiosRequestConfig): Promise<AxiosResponse<UserPublicInfoDto>> {
            return AuthenticationApiFp(configuration).authControllerUserRegister(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {JwtTokens} [body] 
         * @param {string} [xClientType] Client type header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerUserRevoke(body?: JwtTokens, xClientType?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<JwtTokens>> {
            return AuthenticationApiFp(configuration).authControllerUserRevoke(body, xClientType, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * 
     * @param {UserLoginDto} body 
     * @param {string} [xClientType] Client type header
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public async authControllerUserLogin(body: UserLoginDto, xClientType?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<JwtTokens>> {
        return AuthenticationApiFp(this.configuration).authControllerUserLogin(body, xClientType, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {JwtTokens} [body] 
     * @param {string} [xClientType] Client type header
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public async authControllerUserRefresh(body?: JwtTokens, xClientType?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<JwtTokens>> {
        return AuthenticationApiFp(this.configuration).authControllerUserRefresh(body, xClientType, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Register a new user
     * @param {UserRegisterDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public async authControllerUserRegister(body: UserRegisterDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserPublicInfoDto>> {
        return AuthenticationApiFp(this.configuration).authControllerUserRegister(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {JwtTokens} [body] 
     * @param {string} [xClientType] Client type header
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public async authControllerUserRevoke(body?: JwtTokens, xClientType?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<JwtTokens>> {
        return AuthenticationApiFp(this.configuration).authControllerUserRevoke(body, xClientType, options).then((request) => request(this.axios, this.basePath));
    }
}
