/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { LobbyDto } from '../models';
/**
 * LobbyApi - axios parameter creator
 * @export
 */
export const LobbyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new lobby
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lobbyControllerCreateNewLobby: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/lobby`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a list of all public lobbies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lobbyControllerGetAllPublicLobbies: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/lobby/public`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a list of joined lobbies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lobbyControllerGetJoinedLobbies: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/lobby/joined`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Join a lobby
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lobbyControllerJoinLobby: async (code: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            if (code === null || code === undefined) {
                throw new RequiredError('code','Required parameter code was null or undefined when calling lobbyControllerJoinLobby.');
            }
            const localVarPath = `/v1/lobby/join/{code}`
                .replace(`{${"code"}}`, encodeURIComponent(String(code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Launch wg from lobby
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lobbyControllerLaunchWargame: async (code: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            if (code === null || code === undefined) {
                throw new RequiredError('code','Required parameter code was null or undefined when calling lobbyControllerLaunchWargame.');
            }
            const localVarPath = `/v1/lobby/launch/{code}`
                .replace(`{${"code"}}`, encodeURIComponent(String(code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Leave a lobby
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lobbyControllerLeaveLobby: async (code: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            if (code === null || code === undefined) {
                throw new RequiredError('code','Required parameter code was null or undefined when calling lobbyControllerLeaveLobby.');
            }
            const localVarPath = `/v1/lobby/leave/{code}`
                .replace(`{${"code"}}`, encodeURIComponent(String(code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Toggle user ready status
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lobbyControllerToggleUserReady: async (code: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            if (code === null || code === undefined) {
                throw new RequiredError('code','Required parameter code was null or undefined when calling lobbyControllerToggleUserReady.');
            }
            const localVarPath = `/v1/lobby/update/{code}/ready`
                .replace(`{${"code"}}`, encodeURIComponent(String(code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a lobby
         * @param {LobbyDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lobbyControllerUpdateLobby: async (body: LobbyDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling lobbyControllerUpdateLobby.');
            }
            const localVarPath = `/v1/lobby/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LobbyApi - functional programming interface
 * @export
 */
export const LobbyApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new lobby
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerCreateNewLobby(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LobbyDto>>> {
            const localVarAxiosArgs = await LobbyApiAxiosParamCreator(configuration).lobbyControllerCreateNewLobby(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a list of all public lobbies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerGetAllPublicLobbies(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<LobbyDto>>>> {
            const localVarAxiosArgs = await LobbyApiAxiosParamCreator(configuration).lobbyControllerGetAllPublicLobbies(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a list of joined lobbies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerGetJoinedLobbies(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<LobbyDto>>>> {
            const localVarAxiosArgs = await LobbyApiAxiosParamCreator(configuration).lobbyControllerGetJoinedLobbies(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Join a lobby
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerJoinLobby(code: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LobbyDto>>> {
            const localVarAxiosArgs = await LobbyApiAxiosParamCreator(configuration).lobbyControllerJoinLobby(code, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Launch wg from lobby
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerLaunchWargame(code: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LobbyDto>>> {
            const localVarAxiosArgs = await LobbyApiAxiosParamCreator(configuration).lobbyControllerLaunchWargame(code, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Leave a lobby
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerLeaveLobby(code: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await LobbyApiAxiosParamCreator(configuration).lobbyControllerLeaveLobby(code, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Toggle user ready status
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerToggleUserReady(code: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await LobbyApiAxiosParamCreator(configuration).lobbyControllerToggleUserReady(code, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update a lobby
         * @param {LobbyDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerUpdateLobby(body: LobbyDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await LobbyApiAxiosParamCreator(configuration).lobbyControllerUpdateLobby(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * LobbyApi - factory interface
 * @export
 */
export const LobbyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create a new lobby
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerCreateNewLobby(options?: AxiosRequestConfig): Promise<AxiosResponse<LobbyDto>> {
            return LobbyApiFp(configuration).lobbyControllerCreateNewLobby(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a list of all public lobbies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerGetAllPublicLobbies(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<LobbyDto>>> {
            return LobbyApiFp(configuration).lobbyControllerGetAllPublicLobbies(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a list of joined lobbies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerGetJoinedLobbies(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<LobbyDto>>> {
            return LobbyApiFp(configuration).lobbyControllerGetJoinedLobbies(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Join a lobby
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerJoinLobby(code: string, options?: AxiosRequestConfig): Promise<AxiosResponse<LobbyDto>> {
            return LobbyApiFp(configuration).lobbyControllerJoinLobby(code, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Launch wg from lobby
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerLaunchWargame(code: string, options?: AxiosRequestConfig): Promise<AxiosResponse<LobbyDto>> {
            return LobbyApiFp(configuration).lobbyControllerLaunchWargame(code, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Leave a lobby
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerLeaveLobby(code: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return LobbyApiFp(configuration).lobbyControllerLeaveLobby(code, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Toggle user ready status
         * @param {string} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerToggleUserReady(code: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return LobbyApiFp(configuration).lobbyControllerToggleUserReady(code, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a lobby
         * @param {LobbyDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lobbyControllerUpdateLobby(body: LobbyDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return LobbyApiFp(configuration).lobbyControllerUpdateLobby(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LobbyApi - object-oriented interface
 * @export
 * @class LobbyApi
 * @extends {BaseAPI}
 */
export class LobbyApi extends BaseAPI {
    /**
     * 
     * @summary Create a new lobby
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LobbyApi
     */
    public async lobbyControllerCreateNewLobby(options?: AxiosRequestConfig) : Promise<AxiosResponse<LobbyDto>> {
        return LobbyApiFp(this.configuration).lobbyControllerCreateNewLobby(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a list of all public lobbies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LobbyApi
     */
    public async lobbyControllerGetAllPublicLobbies(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<LobbyDto>>> {
        return LobbyApiFp(this.configuration).lobbyControllerGetAllPublicLobbies(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a list of joined lobbies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LobbyApi
     */
    public async lobbyControllerGetJoinedLobbies(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<LobbyDto>>> {
        return LobbyApiFp(this.configuration).lobbyControllerGetJoinedLobbies(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Join a lobby
     * @param {string} code 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LobbyApi
     */
    public async lobbyControllerJoinLobby(code: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<LobbyDto>> {
        return LobbyApiFp(this.configuration).lobbyControllerJoinLobby(code, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Launch wg from lobby
     * @param {string} code 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LobbyApi
     */
    public async lobbyControllerLaunchWargame(code: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<LobbyDto>> {
        return LobbyApiFp(this.configuration).lobbyControllerLaunchWargame(code, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Leave a lobby
     * @param {string} code 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LobbyApi
     */
    public async lobbyControllerLeaveLobby(code: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return LobbyApiFp(this.configuration).lobbyControllerLeaveLobby(code, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Toggle user ready status
     * @param {string} code 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LobbyApi
     */
    public async lobbyControllerToggleUserReady(code: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return LobbyApiFp(this.configuration).lobbyControllerToggleUserReady(code, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update a lobby
     * @param {LobbyDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LobbyApi
     */
    public async lobbyControllerUpdateLobby(body: LobbyDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return LobbyApiFp(this.configuration).lobbyControllerUpdateLobby(body, options).then((request) => request(this.axios, this.basePath));
    }
}
