/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * MailerWpApi - axios parameter creator
 * @export
 */
export const MailerWpApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} email 
         * @param {string} username 
         * @param {string} lang 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mailerWpControllerDevSendTestActivation: async (email: string, username: string, lang: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            if (email === null || email === undefined) {
                throw new RequiredError('email','Required parameter email was null or undefined when calling mailerWpControllerDevSendTestActivation.');
            }
            // verify required parameter 'username' is not null or undefined
            if (username === null || username === undefined) {
                throw new RequiredError('username','Required parameter username was null or undefined when calling mailerWpControllerDevSendTestActivation.');
            }
            // verify required parameter 'lang' is not null or undefined
            if (lang === null || lang === undefined) {
                throw new RequiredError('lang','Required parameter lang was null or undefined when calling mailerWpControllerDevSendTestActivation.');
            }
            const localVarPath = `/v1/dev/mailer-wp/send-test-mail/{email}/{username}/{lang}`
                .replace(`{${"email"}}`, encodeURIComponent(String(email)))
                .replace(`{${"username"}}`, encodeURIComponent(String(username)))
                .replace(`{${"lang"}}`, encodeURIComponent(String(lang)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MailerWpApi - functional programming interface
 * @export
 */
export const MailerWpApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} email 
         * @param {string} username 
         * @param {string} lang 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mailerWpControllerDevSendTestActivation(email: string, username: string, lang: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await MailerWpApiAxiosParamCreator(configuration).mailerWpControllerDevSendTestActivation(email, username, lang, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MailerWpApi - factory interface
 * @export
 */
export const MailerWpApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} email 
         * @param {string} username 
         * @param {string} lang 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mailerWpControllerDevSendTestActivation(email: string, username: string, lang: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return MailerWpApiFp(configuration).mailerWpControllerDevSendTestActivation(email, username, lang, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MailerWpApi - object-oriented interface
 * @export
 * @class MailerWpApi
 * @extends {BaseAPI}
 */
export class MailerWpApi extends BaseAPI {
    /**
     * 
     * @param {string} email 
     * @param {string} username 
     * @param {string} lang 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MailerWpApi
     */
    public async mailerWpControllerDevSendTestActivation(email: string, username: string, lang: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return MailerWpApiFp(this.configuration).mailerWpControllerDevSendTestActivation(email, username, lang, options).then((request) => request(this.axios, this.basePath));
    }
}
