/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { MapDto } from '../models';
/**
 * MapsApi - axios parameter creator
 * @export
 */
export const MapsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a specific map
         * @param {string} mapName name of the map type
         * @param {string} version version of the map ( null &#x3D; \&quot;default\&quot;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mapControllerFindMap: async (mapName: string, version: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mapName' is not null or undefined
            if (mapName === null || mapName === undefined) {
                throw new RequiredError('mapName','Required parameter mapName was null or undefined when calling mapControllerFindMap.');
            }
            // verify required parameter 'version' is not null or undefined
            if (version === null || version === undefined) {
                throw new RequiredError('version','Required parameter version was null or undefined when calling mapControllerFindMap.');
            }
            const localVarPath = `/v1/maps/{mapName}/{version}`
                .replace(`{${"mapName"}}`, encodeURIComponent(String(mapName)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MapsApi - functional programming interface
 * @export
 */
export const MapsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a specific map
         * @param {string} mapName name of the map type
         * @param {string} version version of the map ( null &#x3D; \&quot;default\&quot;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mapControllerFindMap(mapName: string, version: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MapDto>>> {
            const localVarAxiosArgs = await MapsApiAxiosParamCreator(configuration).mapControllerFindMap(mapName, version, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MapsApi - factory interface
 * @export
 */
export const MapsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get a specific map
         * @param {string} mapName name of the map type
         * @param {string} version version of the map ( null &#x3D; \&quot;default\&quot;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mapControllerFindMap(mapName: string, version: string, options?: AxiosRequestConfig): Promise<AxiosResponse<MapDto>> {
            return MapsApiFp(configuration).mapControllerFindMap(mapName, version, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MapsApi - object-oriented interface
 * @export
 * @class MapsApi
 * @extends {BaseAPI}
 */
export class MapsApi extends BaseAPI {
    /**
     * 
     * @summary Get a specific map
     * @param {string} mapName name of the map type
     * @param {string} version version of the map ( null &#x3D; \&quot;default\&quot;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MapsApi
     */
    public async mapControllerFindMap(mapName: string, version: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<MapDto>> {
        return MapsApiFp(this.configuration).mapControllerFindMap(mapName, version, options).then((request) => request(this.axios, this.basePath));
    }
}
