/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { UserDto } from '../models';
import { UserPublicInfoDto } from '../models';
/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a specific user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerDevGetOne: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling userControllerDevGetOne.');
            }
            const localVarPath = `/v1/dev/users/getOnePublic/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test endpoint for API Authentication that returns the UserPublicInfoModel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerDevGetProfile3: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/dev/users/profile3`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get test users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerDevGetTestUsers: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/dev/users/testusers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get authentified user public profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerUserGetAuthUserProfile: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a specific user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerDevGetOne(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserPublicInfoDto>>> {
            const localVarAxiosArgs = await UsersApiAxiosParamCreator(configuration).userControllerDevGetOne(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test endpoint for API Authentication that returns the UserPublicInfoModel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerDevGetProfile3(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserPublicInfoDto>>> {
            const localVarAxiosArgs = await UsersApiAxiosParamCreator(configuration).userControllerDevGetProfile3(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get test users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerDevGetTestUsers(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<UserPublicInfoDto>>>> {
            const localVarAxiosArgs = await UsersApiAxiosParamCreator(configuration).userControllerDevGetTestUsers(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get authentified user public profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerUserGetAuthUserProfile(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserDto>>> {
            const localVarAxiosArgs = await UsersApiAxiosParamCreator(configuration).userControllerUserGetAuthUserProfile(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get a specific user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerDevGetOne(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<UserPublicInfoDto>> {
            return UsersApiFp(configuration).userControllerDevGetOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Test endpoint for API Authentication that returns the UserPublicInfoModel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerDevGetProfile3(options?: AxiosRequestConfig): Promise<AxiosResponse<UserPublicInfoDto>> {
            return UsersApiFp(configuration).userControllerDevGetProfile3(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get test users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerDevGetTestUsers(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<UserPublicInfoDto>>> {
            return UsersApiFp(configuration).userControllerDevGetTestUsers(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get authentified user public profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerUserGetAuthUserProfile(options?: AxiosRequestConfig): Promise<AxiosResponse<UserDto>> {
            return UsersApiFp(configuration).userControllerUserGetAuthUserProfile(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @summary Get a specific user
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public async userControllerDevGetOne(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserPublicInfoDto>> {
        return UsersApiFp(this.configuration).userControllerDevGetOne(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test endpoint for API Authentication that returns the UserPublicInfoModel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public async userControllerDevGetProfile3(options?: AxiosRequestConfig) : Promise<AxiosResponse<UserPublicInfoDto>> {
        return UsersApiFp(this.configuration).userControllerDevGetProfile3(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get test users
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public async userControllerDevGetTestUsers(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<UserPublicInfoDto>>> {
        return UsersApiFp(this.configuration).userControllerDevGetTestUsers(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get authentified user public profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public async userControllerUserGetAuthUserProfile(options?: AxiosRequestConfig) : Promise<AxiosResponse<UserDto>> {
        return UsersApiFp(this.configuration).userControllerUserGetAuthUserProfile(options).then((request) => request(this.axios, this.basePath));
    }
}
