/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { UserEmailChangeDto } from '../models';
import { UserForgottenPasswordResetDto } from '../models';
import { UserPasswordChangeDto } from '../models';
/**
 * UsersAccountApi - axios parameter creator
 * @export
 */
export const UsersAccountApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Authentified user account deletion
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAccountControllerPrivateDeleteAccount: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/users/account/private/delete-account`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Authentified user email change
         * @param {UserEmailChangeDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAccountControllerPrivateEmailChange: async (body: UserEmailChangeDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling userAccountControllerPrivateEmailChange.');
            }
            const localVarPath = `/v1/users/account/private/email-change`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Authentified user password change
         * @param {UserPasswordChangeDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAccountControllerPrivatePasswordChange: async (body: UserPasswordChangeDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling userAccountControllerPrivatePasswordChange.');
            }
            const localVarPath = `/v1/users/account/private/password-change`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Ask for a new account activation email
         * @param {string} usernameOrEmail 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAccountControllerPublicAskForAccountValidationResend: async (usernameOrEmail: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'usernameOrEmail' is not null or undefined
            if (usernameOrEmail === null || usernameOrEmail === undefined) {
                throw new RequiredError('usernameOrEmail','Required parameter usernameOrEmail was null or undefined when calling userAccountControllerPublicAskForAccountValidationResend.');
            }
            const localVarPath = `/v1/users/account/public/validation/send/{usernameOrEmail}`
                .replace(`{${"usernameOrEmail"}}`, encodeURIComponent(String(usernameOrEmail)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Ask for the password-reset mail send
         * @param {string} email user email adress
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAccountControllerPublicAskForResetPasswordEmail: async (email: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            if (email === null || email === undefined) {
                throw new RequiredError('email','Required parameter email was null or undefined when calling userAccountControllerPublicAskForResetPasswordEmail.');
            }
            const localVarPath = `/v1/users/account/public/password-reset/send/{email}`
                .replace(`{${"email"}}`, encodeURIComponent(String(email)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary resetPassword
         * @param {UserForgottenPasswordResetDto} body 
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAccountControllerPublicResetPassword: async (body: UserForgottenPasswordResetDto, token: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling userAccountControllerPublicResetPassword.');
            }
            // verify required parameter 'token' is not null or undefined
            if (token === null || token === undefined) {
                throw new RequiredError('token','Required parameter token was null or undefined when calling userAccountControllerPublicResetPassword.');
            }
            const localVarPath = `/v1/users/account/public/password-reset/{token}`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Account validation email link clicked
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAccountControllerPublicValidateEmail: async (token: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            if (token === null || token === undefined) {
                throw new RequiredError('token','Required parameter token was null or undefined when calling userAccountControllerPublicValidateEmail.');
            }
            const localVarPath = `/v1/users/account/public/validation/{token}`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Validate password reset token
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAccountControllerPublicValidatePasswordResetToken: async (token: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            if (token === null || token === undefined) {
                throw new RequiredError('token','Required parameter token was null or undefined when calling userAccountControllerPublicValidatePasswordResetToken.');
            }
            const localVarPath = `/v1/users/account/public/password-reset/validate/{token}`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersAccountApi - functional programming interface
 * @export
 */
export const UsersAccountApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Authentified user account deletion
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPrivateDeleteAccount(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await UsersAccountApiAxiosParamCreator(configuration).userAccountControllerPrivateDeleteAccount(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Authentified user email change
         * @param {UserEmailChangeDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPrivateEmailChange(body: UserEmailChangeDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await UsersAccountApiAxiosParamCreator(configuration).userAccountControllerPrivateEmailChange(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Authentified user password change
         * @param {UserPasswordChangeDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPrivatePasswordChange(body: UserPasswordChangeDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await UsersAccountApiAxiosParamCreator(configuration).userAccountControllerPrivatePasswordChange(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Ask for a new account activation email
         * @param {string} usernameOrEmail 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPublicAskForAccountValidationResend(usernameOrEmail: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await UsersAccountApiAxiosParamCreator(configuration).userAccountControllerPublicAskForAccountValidationResend(usernameOrEmail, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Ask for the password-reset mail send
         * @param {string} email user email adress
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPublicAskForResetPasswordEmail(email: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await UsersAccountApiAxiosParamCreator(configuration).userAccountControllerPublicAskForResetPasswordEmail(email, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary resetPassword
         * @param {UserForgottenPasswordResetDto} body 
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPublicResetPassword(body: UserForgottenPasswordResetDto, token: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await UsersAccountApiAxiosParamCreator(configuration).userAccountControllerPublicResetPassword(body, token, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Account validation email link clicked
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPublicValidateEmail(token: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await UsersAccountApiAxiosParamCreator(configuration).userAccountControllerPublicValidateEmail(token, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Validate password reset token
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPublicValidatePasswordResetToken(token: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<boolean>>> {
            const localVarAxiosArgs = await UsersAccountApiAxiosParamCreator(configuration).userAccountControllerPublicValidatePasswordResetToken(token, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UsersAccountApi - factory interface
 * @export
 */
export const UsersAccountApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Authentified user account deletion
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPrivateDeleteAccount(options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return UsersAccountApiFp(configuration).userAccountControllerPrivateDeleteAccount(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Authentified user email change
         * @param {UserEmailChangeDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPrivateEmailChange(body: UserEmailChangeDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return UsersAccountApiFp(configuration).userAccountControllerPrivateEmailChange(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Authentified user password change
         * @param {UserPasswordChangeDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPrivatePasswordChange(body: UserPasswordChangeDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return UsersAccountApiFp(configuration).userAccountControllerPrivatePasswordChange(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Ask for a new account activation email
         * @param {string} usernameOrEmail 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPublicAskForAccountValidationResend(usernameOrEmail: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return UsersAccountApiFp(configuration).userAccountControllerPublicAskForAccountValidationResend(usernameOrEmail, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Ask for the password-reset mail send
         * @param {string} email user email adress
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPublicAskForResetPasswordEmail(email: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return UsersAccountApiFp(configuration).userAccountControllerPublicAskForResetPasswordEmail(email, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary resetPassword
         * @param {UserForgottenPasswordResetDto} body 
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPublicResetPassword(body: UserForgottenPasswordResetDto, token: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return UsersAccountApiFp(configuration).userAccountControllerPublicResetPassword(body, token, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Account validation email link clicked
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPublicValidateEmail(token: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return UsersAccountApiFp(configuration).userAccountControllerPublicValidateEmail(token, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Validate password reset token
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAccountControllerPublicValidatePasswordResetToken(token: string, options?: AxiosRequestConfig): Promise<AxiosResponse<boolean>> {
            return UsersAccountApiFp(configuration).userAccountControllerPublicValidatePasswordResetToken(token, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersAccountApi - object-oriented interface
 * @export
 * @class UsersAccountApi
 * @extends {BaseAPI}
 */
export class UsersAccountApi extends BaseAPI {
    /**
     * 
     * @summary Authentified user account deletion
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersAccountApi
     */
    public async userAccountControllerPrivateDeleteAccount(options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return UsersAccountApiFp(this.configuration).userAccountControllerPrivateDeleteAccount(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Authentified user email change
     * @param {UserEmailChangeDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersAccountApi
     */
    public async userAccountControllerPrivateEmailChange(body: UserEmailChangeDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return UsersAccountApiFp(this.configuration).userAccountControllerPrivateEmailChange(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Authentified user password change
     * @param {UserPasswordChangeDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersAccountApi
     */
    public async userAccountControllerPrivatePasswordChange(body: UserPasswordChangeDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return UsersAccountApiFp(this.configuration).userAccountControllerPrivatePasswordChange(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Ask for a new account activation email
     * @param {string} usernameOrEmail 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersAccountApi
     */
    public async userAccountControllerPublicAskForAccountValidationResend(usernameOrEmail: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return UsersAccountApiFp(this.configuration).userAccountControllerPublicAskForAccountValidationResend(usernameOrEmail, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Ask for the password-reset mail send
     * @param {string} email user email adress
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersAccountApi
     */
    public async userAccountControllerPublicAskForResetPasswordEmail(email: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return UsersAccountApiFp(this.configuration).userAccountControllerPublicAskForResetPasswordEmail(email, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary resetPassword
     * @param {UserForgottenPasswordResetDto} body 
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersAccountApi
     */
    public async userAccountControllerPublicResetPassword(body: UserForgottenPasswordResetDto, token: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return UsersAccountApiFp(this.configuration).userAccountControllerPublicResetPassword(body, token, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Account validation email link clicked
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersAccountApi
     */
    public async userAccountControllerPublicValidateEmail(token: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return UsersAccountApiFp(this.configuration).userAccountControllerPublicValidateEmail(token, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Validate password reset token
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersAccountApi
     */
    public async userAccountControllerPublicValidatePasswordResetToken(token: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<boolean>> {
        return UsersAccountApiFp(this.configuration).userAccountControllerPublicValidatePasswordResetToken(token, options).then((request) => request(this.axios, this.basePath));
    }
}
