/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * UsersWgListApi - axios parameter creator
 * @export
 */
export const UsersWgListApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all related wargames ids of the authentified user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userWgsControllerFindByAuth: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/users/wgs/byAuth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersWgListApi - functional programming interface
 * @export
 */
export const UsersWgListApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all related wargames ids of the authentified user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userWgsControllerFindByAuth(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<string>>>> {
            const localVarAxiosArgs = await UsersWgListApiAxiosParamCreator(configuration).userWgsControllerFindByAuth(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UsersWgListApi - factory interface
 * @export
 */
export const UsersWgListApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get all related wargames ids of the authentified user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userWgsControllerFindByAuth(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<string>>> {
            return UsersWgListApiFp(configuration).userWgsControllerFindByAuth(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersWgListApi - object-oriented interface
 * @export
 * @class UsersWgListApi
 * @extends {BaseAPI}
 */
export class UsersWgListApi extends BaseAPI {
    /**
     * 
     * @summary Get all related wargames ids of the authentified user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersWgListApi
     */
    public async userWgsControllerFindByAuth(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<string>>> {
        return UsersWgListApiFp(this.configuration).userWgsControllerFindByAuth(options).then((request) => request(this.axios, this.basePath));
    }
}
