/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ActiveWgsListDto } from '../models';
import { WgDto } from '../models';
import { WgGroupedDto } from '../models';
import { WgGroupedDtoPhaseUpdate } from '../models';
/**
 * WargamesApi - axios parameter creator
 * @export
 */
export const WargamesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Test how many IDs Cassandra can handle in an IN clause
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgControllerDevTestMany: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/dev/wgs/by/ids/test`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Forfeit a wargame
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgControllerForfeitWgByAuth: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling wgControllerForfeitWgByAuth.');
            }
            const localVarPath = `/v1/wgs/{id}/forfeit`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get current user active wargames
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgControllerGetActiveWgsByAuth: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/wgs/byAuth/active`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get current user archived wargames
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgControllerGetArchivedWgsByAuth: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/wgs/byAuth/archived`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a specific wargame
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgControllerGetOne: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling wgControllerGetOne.');
            }
            const localVarPath = `/v1/wgs/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a wargame grouped data for phase update
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgControllerGetOneByAuthGroupedPhaseUpdate: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling wgControllerGetOneByAuthGroupedPhaseUpdate.');
            }
            const localVarPath = `/v1/wgs/grouped/{id}/phaseUpdate`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a wargame grouped data
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgControllerGetOneGroupedByAuth: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling wgControllerGetOneGroupedByAuth.');
            }
            const localVarPath = `/v1/wgs/grouped/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WargamesApi - functional programming interface
 * @export
 */
export const WargamesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Test how many IDs Cassandra can handle in an IN clause
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerDevTestMany(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WargamesApiAxiosParamCreator(configuration).wgControllerDevTestMany(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Forfeit a wargame
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerForfeitWgByAuth(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WargamesApiAxiosParamCreator(configuration).wgControllerForfeitWgByAuth(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get current user active wargames
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerGetActiveWgsByAuth(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ActiveWgsListDto>>> {
            const localVarAxiosArgs = await WargamesApiAxiosParamCreator(configuration).wgControllerGetActiveWgsByAuth(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get current user archived wargames
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerGetArchivedWgsByAuth(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<WgDto>>>> {
            const localVarAxiosArgs = await WargamesApiAxiosParamCreator(configuration).wgControllerGetArchivedWgsByAuth(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a specific wargame
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerGetOne(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WgDto>>> {
            const localVarAxiosArgs = await WargamesApiAxiosParamCreator(configuration).wgControllerGetOne(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a wargame grouped data for phase update
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerGetOneByAuthGroupedPhaseUpdate(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WgGroupedDtoPhaseUpdate>>> {
            const localVarAxiosArgs = await WargamesApiAxiosParamCreator(configuration).wgControllerGetOneByAuthGroupedPhaseUpdate(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a wargame grouped data
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerGetOneGroupedByAuth(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WgGroupedDto>>> {
            const localVarAxiosArgs = await WargamesApiAxiosParamCreator(configuration).wgControllerGetOneGroupedByAuth(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WargamesApi - factory interface
 * @export
 */
export const WargamesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Test how many IDs Cassandra can handle in an IN clause
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerDevTestMany(options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WargamesApiFp(configuration).wgControllerDevTestMany(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Forfeit a wargame
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerForfeitWgByAuth(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WargamesApiFp(configuration).wgControllerForfeitWgByAuth(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get current user active wargames
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerGetActiveWgsByAuth(options?: AxiosRequestConfig): Promise<AxiosResponse<ActiveWgsListDto>> {
            return WargamesApiFp(configuration).wgControllerGetActiveWgsByAuth(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get current user archived wargames
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerGetArchivedWgsByAuth(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<WgDto>>> {
            return WargamesApiFp(configuration).wgControllerGetArchivedWgsByAuth(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a specific wargame
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerGetOne(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<WgDto>> {
            return WargamesApiFp(configuration).wgControllerGetOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a wargame grouped data for phase update
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerGetOneByAuthGroupedPhaseUpdate(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<WgGroupedDtoPhaseUpdate>> {
            return WargamesApiFp(configuration).wgControllerGetOneByAuthGroupedPhaseUpdate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a wargame grouped data
         * @param {string} id Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgControllerGetOneGroupedByAuth(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<WgGroupedDto>> {
            return WargamesApiFp(configuration).wgControllerGetOneGroupedByAuth(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WargamesApi - object-oriented interface
 * @export
 * @class WargamesApi
 * @extends {BaseAPI}
 */
export class WargamesApi extends BaseAPI {
    /**
     * 
     * @summary Test how many IDs Cassandra can handle in an IN clause
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesApi
     */
    public async wgControllerDevTestMany(options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WargamesApiFp(this.configuration).wgControllerDevTestMany(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Forfeit a wargame
     * @param {string} id Id of the Wargame
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesApi
     */
    public async wgControllerForfeitWgByAuth(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WargamesApiFp(this.configuration).wgControllerForfeitWgByAuth(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get current user active wargames
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesApi
     */
    public async wgControllerGetActiveWgsByAuth(options?: AxiosRequestConfig) : Promise<AxiosResponse<ActiveWgsListDto>> {
        return WargamesApiFp(this.configuration).wgControllerGetActiveWgsByAuth(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get current user archived wargames
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesApi
     */
    public async wgControllerGetArchivedWgsByAuth(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<WgDto>>> {
        return WargamesApiFp(this.configuration).wgControllerGetArchivedWgsByAuth(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a specific wargame
     * @param {string} id Id of the Wargame
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesApi
     */
    public async wgControllerGetOne(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<WgDto>> {
        return WargamesApiFp(this.configuration).wgControllerGetOne(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a wargame grouped data for phase update
     * @param {string} id Id of the Wargame
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesApi
     */
    public async wgControllerGetOneByAuthGroupedPhaseUpdate(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<WgGroupedDtoPhaseUpdate>> {
        return WargamesApiFp(this.configuration).wgControllerGetOneByAuthGroupedPhaseUpdate(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a wargame grouped data
     * @param {string} id Id of the Wargame
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesApi
     */
    public async wgControllerGetOneGroupedByAuth(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<WgGroupedDto>> {
        return WargamesApiFp(this.configuration).wgControllerGetOneGroupedByAuth(id, options).then((request) => request(this.axios, this.basePath));
    }
}
