/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { WgArchivesDto } from '../models';
/**
 * WargamesArchivesApi - axios parameter creator
 * @export
 */
export const WargamesArchivesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgArchivesControllerDevGetAll: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/dev/wgArchives`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a specific wg archive
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgArchivesControllerDevGetOne: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgArchivesControllerDevGetOne.');
            }
            const localVarPath = `/v1/dev/wgArchives/{wgId}`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a wargame archive
         * @param {string} wgId Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgArchivesControllerGetOne: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgArchivesControllerGetOne.');
            }
            const localVarPath = `/v1/wgArchives/{wgId}`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WargamesArchivesApi - functional programming interface
 * @export
 */
export const WargamesArchivesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgArchivesControllerDevGetAll(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WargamesArchivesApiAxiosParamCreator(configuration).wgArchivesControllerDevGetAll(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a specific wg archive
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgArchivesControllerDevGetOne(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WargamesArchivesApiAxiosParamCreator(configuration).wgArchivesControllerDevGetOne(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a wargame archive
         * @param {string} wgId Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgArchivesControllerGetOne(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WgArchivesDto>>> {
            const localVarAxiosArgs = await WargamesArchivesApiAxiosParamCreator(configuration).wgArchivesControllerGetOne(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WargamesArchivesApi - factory interface
 * @export
 */
export const WargamesArchivesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgArchivesControllerDevGetAll(options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WargamesArchivesApiFp(configuration).wgArchivesControllerDevGetAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a specific wg archive
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgArchivesControllerDevGetOne(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WargamesArchivesApiFp(configuration).wgArchivesControllerDevGetOne(wgId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a wargame archive
         * @param {string} wgId Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgArchivesControllerGetOne(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<WgArchivesDto>> {
            return WargamesArchivesApiFp(configuration).wgArchivesControllerGetOne(wgId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WargamesArchivesApi - object-oriented interface
 * @export
 * @class WargamesArchivesApi
 * @extends {BaseAPI}
 */
export class WargamesArchivesApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesArchivesApi
     */
    public async wgArchivesControllerDevGetAll(options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WargamesArchivesApiFp(this.configuration).wgArchivesControllerDevGetAll(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a specific wg archive
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesArchivesApi
     */
    public async wgArchivesControllerDevGetOne(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WargamesArchivesApiFp(this.configuration).wgArchivesControllerDevGetOne(wgId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a wargame archive
     * @param {string} wgId Id of the Wargame
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesArchivesApi
     */
    public async wgArchivesControllerGetOne(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<WgArchivesDto>> {
        return WargamesArchivesApiFp(this.configuration).wgArchivesControllerGetOne(wgId, options).then((request) => request(this.axios, this.basePath));
    }
}
