/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { WgLockDto } from '../models';
/**
 * WargamesLocksApi - axios parameter creator
 * @export
 */
export const WargamesLocksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get locks for a wg phase
         * @param {string} wgId Id of the Wargame
         * @param {number} phase Phase of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgLockControllerDevGetLocksAtPhase: async (wgId: string, phase: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgLockControllerDevGetLocksAtPhase.');
            }
            // verify required parameter 'phase' is not null or undefined
            if (phase === null || phase === undefined) {
                throw new RequiredError('phase','Required parameter phase was null or undefined when calling wgLockControllerDevGetLocksAtPhase.');
            }
            const localVarPath = `/v1/dev/wgs/{wgId}/locks/phase/{phase}`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)))
                .replace(`{${"phase"}}`, encodeURIComponent(String(phase)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Set lock for an auth user
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgLockControllerLockWgAuthUser: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgLockControllerLockWgAuthUser.');
            }
            const localVarPath = `/v1/wgs/{wgId}/locks`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Set unlock for an auth user
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgLockControllerUnlockWgAuthUser: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgLockControllerUnlockWgAuthUser.');
            }
            const localVarPath = `/v1/wgs/{wgId}/locks/unlock`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WargamesLocksApi - functional programming interface
 * @export
 */
export const WargamesLocksApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get locks for a wg phase
         * @param {string} wgId Id of the Wargame
         * @param {number} phase Phase of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgLockControllerDevGetLocksAtPhase(wgId: string, phase: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WgLockDto>>> {
            const localVarAxiosArgs = await WargamesLocksApiAxiosParamCreator(configuration).wgLockControllerDevGetLocksAtPhase(wgId, phase, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Set lock for an auth user
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgLockControllerLockWgAuthUser(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WgLockDto>>> {
            const localVarAxiosArgs = await WargamesLocksApiAxiosParamCreator(configuration).wgLockControllerLockWgAuthUser(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Set unlock for an auth user
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgLockControllerUnlockWgAuthUser(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WgLockDto>>> {
            const localVarAxiosArgs = await WargamesLocksApiAxiosParamCreator(configuration).wgLockControllerUnlockWgAuthUser(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WargamesLocksApi - factory interface
 * @export
 */
export const WargamesLocksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get locks for a wg phase
         * @param {string} wgId Id of the Wargame
         * @param {number} phase Phase of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgLockControllerDevGetLocksAtPhase(wgId: string, phase: number, options?: AxiosRequestConfig): Promise<AxiosResponse<WgLockDto>> {
            return WargamesLocksApiFp(configuration).wgLockControllerDevGetLocksAtPhase(wgId, phase, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Set lock for an auth user
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgLockControllerLockWgAuthUser(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<WgLockDto>> {
            return WargamesLocksApiFp(configuration).wgLockControllerLockWgAuthUser(wgId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Set unlock for an auth user
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgLockControllerUnlockWgAuthUser(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<WgLockDto>> {
            return WargamesLocksApiFp(configuration).wgLockControllerUnlockWgAuthUser(wgId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WargamesLocksApi - object-oriented interface
 * @export
 * @class WargamesLocksApi
 * @extends {BaseAPI}
 */
export class WargamesLocksApi extends BaseAPI {
    /**
     * 
     * @summary Get locks for a wg phase
     * @param {string} wgId Id of the Wargame
     * @param {number} phase Phase of the Wargame
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesLocksApi
     */
    public async wgLockControllerDevGetLocksAtPhase(wgId: string, phase: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<WgLockDto>> {
        return WargamesLocksApiFp(this.configuration).wgLockControllerDevGetLocksAtPhase(wgId, phase, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Set lock for an auth user
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesLocksApi
     */
    public async wgLockControllerLockWgAuthUser(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<WgLockDto>> {
        return WargamesLocksApiFp(this.configuration).wgLockControllerLockWgAuthUser(wgId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Set unlock for an auth user
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesLocksApi
     */
    public async wgLockControllerUnlockWgAuthUser(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<WgLockDto>> {
        return WargamesLocksApiFp(this.configuration).wgLockControllerUnlockWgAuthUser(wgId, options).then((request) => request(this.axios, this.basePath));
    }
}
