/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { WgMuteDto } from '../models';
/**
 * WargamesMutesApi - axios parameter creator
 * @export
 */
export const WargamesMutesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {WgMuteDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgMuteControllerMute: async (body: WgMuteDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling wgMuteControllerMute.');
            }
            const localVarPath = `/v1/wgs/mutes/mute`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {WgMuteDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgMuteControllerUnmute: async (body: WgMuteDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling wgMuteControllerUnmute.');
            }
            const localVarPath = `/v1/wgs/mutes/unmute`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WargamesMutesApi - functional programming interface
 * @export
 */
export const WargamesMutesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {WgMuteDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgMuteControllerMute(body: WgMuteDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WargamesMutesApiAxiosParamCreator(configuration).wgMuteControllerMute(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {WgMuteDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgMuteControllerUnmute(body: WgMuteDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WargamesMutesApiAxiosParamCreator(configuration).wgMuteControllerUnmute(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WargamesMutesApi - factory interface
 * @export
 */
export const WargamesMutesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {WgMuteDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgMuteControllerMute(body: WgMuteDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WargamesMutesApiFp(configuration).wgMuteControllerMute(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {WgMuteDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgMuteControllerUnmute(body: WgMuteDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WargamesMutesApiFp(configuration).wgMuteControllerUnmute(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WargamesMutesApi - object-oriented interface
 * @export
 * @class WargamesMutesApi
 * @extends {BaseAPI}
 */
export class WargamesMutesApi extends BaseAPI {
    /**
     * 
     * @param {WgMuteDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesMutesApi
     */
    public async wgMuteControllerMute(body: WgMuteDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WargamesMutesApiFp(this.configuration).wgMuteControllerMute(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {WgMuteDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesMutesApi
     */
    public async wgMuteControllerUnmute(body: WgMuteDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WargamesMutesApiFp(this.configuration).wgMuteControllerUnmute(body, options).then((request) => request(this.axios, this.basePath));
    }
}
