/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CreateWgActionDto } from '../models';
import { WgActionDto } from '../models';
import { WgStateDto } from '../models';
/**
 * WargamesActionsApi - axios parameter creator
 * @export
 */
export const WargamesActionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Find all Actions in a Wargame
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgActionControllerGetAll: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgActionControllerGetAll.');
            }
            const localVarPath = `/v1/wgs/{wgId}/actions`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find all Actions in a Wargame phase
         * @param {string} wgId 
         * @param {number} phase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgActionControllerGetAllAtPhase: async (wgId: string, phase: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgActionControllerGetAllAtPhase.');
            }
            // verify required parameter 'phase' is not null or undefined
            if (phase === null || phase === undefined) {
                throw new RequiredError('phase','Required parameter phase was null or undefined when calling wgActionControllerGetAllAtPhase.');
            }
            const localVarPath = `/v1/wgs/{wgId}/actions/phase/{phase}`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)))
                .replace(`{${"phase"}}`, encodeURIComponent(String(phase)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Find a specific Action in a Wargame
         * @param {string} wgId 
         * @param {number} phase 
         * @param {string} territory 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgActionControllerGetOne: async (wgId: string, phase: number, territory: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgActionControllerGetOne.');
            }
            // verify required parameter 'phase' is not null or undefined
            if (phase === null || phase === undefined) {
                throw new RequiredError('phase','Required parameter phase was null or undefined when calling wgActionControllerGetOne.');
            }
            // verify required parameter 'territory' is not null or undefined
            if (territory === null || territory === undefined) {
                throw new RequiredError('territory','Required parameter territory was null or undefined when calling wgActionControllerGetOne.');
            }
            const localVarPath = `/v1/wgs/{wgId}/actions/phase/{phase}/{territory}`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)))
                .replace(`{${"phase"}}`, encodeURIComponent(String(phase)))
                .replace(`{${"territory"}}`, encodeURIComponent(String(territory)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new action
         * @param {CreateWgActionDto} body 
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgActionControllerPostAction: async (body: CreateWgActionDto, wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling wgActionControllerPostAction.');
            }
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgActionControllerPostAction.');
            }
            const localVarPath = `/v1/wgs/{wgId}/actions`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WargamesActionsApi - functional programming interface
 * @export
 */
export const WargamesActionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Find all Actions in a Wargame
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgActionControllerGetAll(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<WgActionDto>>>> {
            const localVarAxiosArgs = await WargamesActionsApiAxiosParamCreator(configuration).wgActionControllerGetAll(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Find all Actions in a Wargame phase
         * @param {string} wgId 
         * @param {number} phase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgActionControllerGetAllAtPhase(wgId: string, phase: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<WgActionDto>>>> {
            const localVarAxiosArgs = await WargamesActionsApiAxiosParamCreator(configuration).wgActionControllerGetAllAtPhase(wgId, phase, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Find a specific Action in a Wargame
         * @param {string} wgId 
         * @param {number} phase 
         * @param {string} territory 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgActionControllerGetOne(wgId: string, phase: number, territory: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WgActionDto>>> {
            const localVarAxiosArgs = await WargamesActionsApiAxiosParamCreator(configuration).wgActionControllerGetOne(wgId, phase, territory, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create a new action
         * @param {CreateWgActionDto} body 
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgActionControllerPostAction(body: CreateWgActionDto, wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WgStateDto>>> {
            const localVarAxiosArgs = await WargamesActionsApiAxiosParamCreator(configuration).wgActionControllerPostAction(body, wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WargamesActionsApi - factory interface
 * @export
 */
export const WargamesActionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Find all Actions in a Wargame
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgActionControllerGetAll(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<WgActionDto>>> {
            return WargamesActionsApiFp(configuration).wgActionControllerGetAll(wgId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find all Actions in a Wargame phase
         * @param {string} wgId 
         * @param {number} phase 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgActionControllerGetAllAtPhase(wgId: string, phase: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<WgActionDto>>> {
            return WargamesActionsApiFp(configuration).wgActionControllerGetAllAtPhase(wgId, phase, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Find a specific Action in a Wargame
         * @param {string} wgId 
         * @param {number} phase 
         * @param {string} territory 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgActionControllerGetOne(wgId: string, phase: number, territory: string, options?: AxiosRequestConfig): Promise<AxiosResponse<WgActionDto>> {
            return WargamesActionsApiFp(configuration).wgActionControllerGetOne(wgId, phase, territory, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new action
         * @param {CreateWgActionDto} body 
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgActionControllerPostAction(body: CreateWgActionDto, wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<WgStateDto>> {
            return WargamesActionsApiFp(configuration).wgActionControllerPostAction(body, wgId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WargamesActionsApi - object-oriented interface
 * @export
 * @class WargamesActionsApi
 * @extends {BaseAPI}
 */
export class WargamesActionsApi extends BaseAPI {
    /**
     * 
     * @summary Find all Actions in a Wargame
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesActionsApi
     */
    public async wgActionControllerGetAll(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<WgActionDto>>> {
        return WargamesActionsApiFp(this.configuration).wgActionControllerGetAll(wgId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Find all Actions in a Wargame phase
     * @param {string} wgId 
     * @param {number} phase 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesActionsApi
     */
    public async wgActionControllerGetAllAtPhase(wgId: string, phase: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<WgActionDto>>> {
        return WargamesActionsApiFp(this.configuration).wgActionControllerGetAllAtPhase(wgId, phase, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Find a specific Action in a Wargame
     * @param {string} wgId 
     * @param {number} phase 
     * @param {string} territory 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesActionsApi
     */
    public async wgActionControllerGetOne(wgId: string, phase: number, territory: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<WgActionDto>> {
        return WargamesActionsApiFp(this.configuration).wgActionControllerGetOne(wgId, phase, territory, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create a new action
     * @param {CreateWgActionDto} body 
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesActionsApi
     */
    public async wgActionControllerPostAction(body: CreateWgActionDto, wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<WgStateDto>> {
        return WargamesActionsApiFp(this.configuration).wgActionControllerPostAction(body, wgId, options).then((request) => request(this.axios, this.basePath));
    }
}
