/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { WgStateDto } from '../models';
/**
 * WargamesStatesApi - axios parameter creator
 * @export
 */
export const WargamesStatesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a specific Wargame state with the Wargame ID and current phase
         * @param {string} wgId Id of the Wargame
         * @param {number} phase Phase number to look for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgStateControllerGetState: async (wgId: string, phase: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgStateControllerGetState.');
            }
            // verify required parameter 'phase' is not null or undefined
            if (phase === null || phase === undefined) {
                throw new RequiredError('phase','Required parameter phase was null or undefined when calling wgStateControllerGetState.');
            }
            const localVarPath = `/v1/wgs/{wgId}/states/phase/{phase}`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)))
                .replace(`{${"phase"}}`, encodeURIComponent(String(phase)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a specific Wargame state with the Wargame ID and current phase
         * @param {string} wgId Id of the Wargame
         * @param {number} phase Phase number to look for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgStateControllerGetStateFiltered: async (wgId: string, phase: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgStateControllerGetStateFiltered.');
            }
            // verify required parameter 'phase' is not null or undefined
            if (phase === null || phase === undefined) {
                throw new RequiredError('phase','Required parameter phase was null or undefined when calling wgStateControllerGetStateFiltered.');
            }
            const localVarPath = `/v1/wgs/{wgId}/states/phase/{phase}/filtered`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)))
                .replace(`{${"phase"}}`, encodeURIComponent(String(phase)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all Wargame states with a Wargame ID
         * @param {string} wgId Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgStateControllerGetStatesByWgId: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgStateControllerGetStatesByWgId.');
            }
            const localVarPath = `/v1/wgs/{wgId}/states`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WargamesStatesApi - functional programming interface
 * @export
 */
export const WargamesStatesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get a specific Wargame state with the Wargame ID and current phase
         * @param {string} wgId Id of the Wargame
         * @param {number} phase Phase number to look for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgStateControllerGetState(wgId: string, phase: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WgStateDto>>> {
            const localVarAxiosArgs = await WargamesStatesApiAxiosParamCreator(configuration).wgStateControllerGetState(wgId, phase, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get a specific Wargame state with the Wargame ID and current phase
         * @param {string} wgId Id of the Wargame
         * @param {number} phase Phase number to look for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgStateControllerGetStateFiltered(wgId: string, phase: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WgStateDto>>> {
            const localVarAxiosArgs = await WargamesStatesApiAxiosParamCreator(configuration).wgStateControllerGetStateFiltered(wgId, phase, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get all Wargame states with a Wargame ID
         * @param {string} wgId Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgStateControllerGetStatesByWgId(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<WgStateDto>>>> {
            const localVarAxiosArgs = await WargamesStatesApiAxiosParamCreator(configuration).wgStateControllerGetStatesByWgId(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WargamesStatesApi - factory interface
 * @export
 */
export const WargamesStatesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get a specific Wargame state with the Wargame ID and current phase
         * @param {string} wgId Id of the Wargame
         * @param {number} phase Phase number to look for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgStateControllerGetState(wgId: string, phase: number, options?: AxiosRequestConfig): Promise<AxiosResponse<WgStateDto>> {
            return WargamesStatesApiFp(configuration).wgStateControllerGetState(wgId, phase, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a specific Wargame state with the Wargame ID and current phase
         * @param {string} wgId Id of the Wargame
         * @param {number} phase Phase number to look for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgStateControllerGetStateFiltered(wgId: string, phase: number, options?: AxiosRequestConfig): Promise<AxiosResponse<WgStateDto>> {
            return WargamesStatesApiFp(configuration).wgStateControllerGetStateFiltered(wgId, phase, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all Wargame states with a Wargame ID
         * @param {string} wgId Id of the Wargame
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgStateControllerGetStatesByWgId(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<WgStateDto>>> {
            return WargamesStatesApiFp(configuration).wgStateControllerGetStatesByWgId(wgId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WargamesStatesApi - object-oriented interface
 * @export
 * @class WargamesStatesApi
 * @extends {BaseAPI}
 */
export class WargamesStatesApi extends BaseAPI {
    /**
     * Get a specific Wargame state with the Wargame ID and current phase
     * @param {string} wgId Id of the Wargame
     * @param {number} phase Phase number to look for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesStatesApi
     */
    public async wgStateControllerGetState(wgId: string, phase: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<WgStateDto>> {
        return WargamesStatesApiFp(this.configuration).wgStateControllerGetState(wgId, phase, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get a specific Wargame state with the Wargame ID and current phase
     * @param {string} wgId Id of the Wargame
     * @param {number} phase Phase number to look for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesStatesApi
     */
    public async wgStateControllerGetStateFiltered(wgId: string, phase: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<WgStateDto>> {
        return WargamesStatesApiFp(this.configuration).wgStateControllerGetStateFiltered(wgId, phase, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get all Wargame states with a Wargame ID
     * @param {string} wgId Id of the Wargame
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesStatesApi
     */
    public async wgStateControllerGetStatesByWgId(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<WgStateDto>>> {
        return WargamesStatesApiFp(this.configuration).wgStateControllerGetStatesByWgId(wgId, options).then((request) => request(this.axios, this.basePath));
    }
}
