/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CreateWgMessengerDtoPlayer2PlayerBody } from '../models';
import { WgMessengerDto } from '../models';
/**
 * WargamesMessengerApi - axios parameter creator
 * @export
 */
export const WargamesMessengerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all messages of the current authUser in a wg
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgMessengerControllerGetManyByAuth: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgMessengerControllerGetManyByAuth.');
            }
            const localVarPath = `/v1/wgs/{wgId}/messenger`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Send a message from the current authUser to another player in the same wg
         * @param {CreateWgMessengerDtoPlayer2PlayerBody} body 
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgMessengerControllerSendPlayer2PlayerMessage: async (body: CreateWgMessengerDtoPlayer2PlayerBody, wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling wgMessengerControllerSendPlayer2PlayerMessage.');
            }
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgMessengerControllerSendPlayer2PlayerMessage.');
            }
            const localVarPath = `/v1/wgs/{wgId}/messenger`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WargamesMessengerApi - functional programming interface
 * @export
 */
export const WargamesMessengerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all messages of the current authUser in a wg
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgMessengerControllerGetManyByAuth(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<WgMessengerDto>>>> {
            const localVarAxiosArgs = await WargamesMessengerApiAxiosParamCreator(configuration).wgMessengerControllerGetManyByAuth(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Send a message from the current authUser to another player in the same wg
         * @param {CreateWgMessengerDtoPlayer2PlayerBody} body 
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgMessengerControllerSendPlayer2PlayerMessage(body: CreateWgMessengerDtoPlayer2PlayerBody, wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WargamesMessengerApiAxiosParamCreator(configuration).wgMessengerControllerSendPlayer2PlayerMessage(body, wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WargamesMessengerApi - factory interface
 * @export
 */
export const WargamesMessengerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get all messages of the current authUser in a wg
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgMessengerControllerGetManyByAuth(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<WgMessengerDto>>> {
            return WargamesMessengerApiFp(configuration).wgMessengerControllerGetManyByAuth(wgId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Send a message from the current authUser to another player in the same wg
         * @param {CreateWgMessengerDtoPlayer2PlayerBody} body 
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgMessengerControllerSendPlayer2PlayerMessage(body: CreateWgMessengerDtoPlayer2PlayerBody, wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WargamesMessengerApiFp(configuration).wgMessengerControllerSendPlayer2PlayerMessage(body, wgId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WargamesMessengerApi - object-oriented interface
 * @export
 * @class WargamesMessengerApi
 * @extends {BaseAPI}
 */
export class WargamesMessengerApi extends BaseAPI {
    /**
     * 
     * @summary Get all messages of the current authUser in a wg
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesMessengerApi
     */
    public async wgMessengerControllerGetManyByAuth(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<WgMessengerDto>>> {
        return WargamesMessengerApiFp(this.configuration).wgMessengerControllerGetManyByAuth(wgId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Send a message from the current authUser to another player in the same wg
     * @param {CreateWgMessengerDtoPlayer2PlayerBody} body 
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WargamesMessengerApi
     */
    public async wgMessengerControllerSendPlayer2PlayerMessage(body: CreateWgMessengerDtoPlayer2PlayerBody, wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WargamesMessengerApiFp(this.configuration).wgMessengerControllerSendPlayer2PlayerMessage(body, wgId, options).then((request) => request(this.axios, this.basePath));
    }
}
