/* tslint:disable */
/* eslint-disable */
/**
 * Battlecorp Horizon
 * Public API for developers
 *
 * OpenAPI spec version: 1.0
 * Contact: admin@battlecorp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * WgResolutionApi - axios parameter creator
 * @export
 */
export const WgResolutionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Dev next phase
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgResolutionControllerDevNextPhase: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgResolutionControllerDevNextPhase.');
            }
            const localVarPath = `/v1/dev/wgs/{wgId}/resolution/nextPhase`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Dev next phase patch
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgResolutionControllerDevNextPhasePatch: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgResolutionControllerDevNextPhasePatch.');
            }
            const localVarPath = `/v1/dev/wgs/{wgId}/resolution/nextPhasePatch`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Dev previous phase
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgResolutionControllerDevPrevPhase: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgResolutionControllerDevPrevPhase.');
            }
            const localVarPath = `/v1/dev/wgs/{wgId}/resolution/prevPhase`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Dev previous phase patch
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgResolutionControllerDevPrevPhasePatch: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgResolutionControllerDevPrevPhasePatch.');
            }
            const localVarPath = `/v1/dev/wgs/{wgId}/resolution/prevPhasePatch`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Dev resetWargame
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wgResolutionControllerDevResetWargame: async (wgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wgId' is not null or undefined
            if (wgId === null || wgId === undefined) {
                throw new RequiredError('wgId','Required parameter wgId was null or undefined when calling wgResolutionControllerDevResetWargame.');
            }
            const localVarPath = `/v1/dev/wgs/{wgId}/resolution/resetWargame`
                .replace(`{${"wgId"}}`, encodeURIComponent(String(wgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WgResolutionApi - functional programming interface
 * @export
 */
export const WgResolutionApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Dev next phase
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgResolutionControllerDevNextPhase(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WgResolutionApiAxiosParamCreator(configuration).wgResolutionControllerDevNextPhase(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Dev next phase patch
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgResolutionControllerDevNextPhasePatch(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WgResolutionApiAxiosParamCreator(configuration).wgResolutionControllerDevNextPhasePatch(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Dev previous phase
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgResolutionControllerDevPrevPhase(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WgResolutionApiAxiosParamCreator(configuration).wgResolutionControllerDevPrevPhase(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Dev previous phase patch
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgResolutionControllerDevPrevPhasePatch(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WgResolutionApiAxiosParamCreator(configuration).wgResolutionControllerDevPrevPhasePatch(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Dev resetWargame
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgResolutionControllerDevResetWargame(wgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WgResolutionApiAxiosParamCreator(configuration).wgResolutionControllerDevResetWargame(wgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WgResolutionApi - factory interface
 * @export
 */
export const WgResolutionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Dev next phase
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgResolutionControllerDevNextPhase(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WgResolutionApiFp(configuration).wgResolutionControllerDevNextPhase(wgId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Dev next phase patch
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgResolutionControllerDevNextPhasePatch(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WgResolutionApiFp(configuration).wgResolutionControllerDevNextPhasePatch(wgId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Dev previous phase
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgResolutionControllerDevPrevPhase(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WgResolutionApiFp(configuration).wgResolutionControllerDevPrevPhase(wgId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Dev previous phase patch
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgResolutionControllerDevPrevPhasePatch(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WgResolutionApiFp(configuration).wgResolutionControllerDevPrevPhasePatch(wgId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Dev resetWargame
         * @param {string} wgId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wgResolutionControllerDevResetWargame(wgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WgResolutionApiFp(configuration).wgResolutionControllerDevResetWargame(wgId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WgResolutionApi - object-oriented interface
 * @export
 * @class WgResolutionApi
 * @extends {BaseAPI}
 */
export class WgResolutionApi extends BaseAPI {
    /**
     * 
     * @summary Dev next phase
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WgResolutionApi
     */
    public async wgResolutionControllerDevNextPhase(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WgResolutionApiFp(this.configuration).wgResolutionControllerDevNextPhase(wgId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Dev next phase patch
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WgResolutionApi
     */
    public async wgResolutionControllerDevNextPhasePatch(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WgResolutionApiFp(this.configuration).wgResolutionControllerDevNextPhasePatch(wgId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Dev previous phase
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WgResolutionApi
     */
    public async wgResolutionControllerDevPrevPhase(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WgResolutionApiFp(this.configuration).wgResolutionControllerDevPrevPhase(wgId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Dev previous phase patch
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WgResolutionApi
     */
    public async wgResolutionControllerDevPrevPhasePatch(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WgResolutionApiFp(this.configuration).wgResolutionControllerDevPrevPhasePatch(wgId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Dev resetWargame
     * @param {string} wgId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WgResolutionApi
     */
    public async wgResolutionControllerDevResetWargame(wgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WgResolutionApiFp(this.configuration).wgResolutionControllerDevResetWargame(wgId, options).then((request) => request(this.axios, this.basePath));
    }
}
